### ISSUE TITLE
Extensive documentation for pagination

### ISSUE THREAD

**Issue by childersd** [ngneat/elf#102]
### Which @ngneat/elf-* package(s) are relevant/releated to the feature request?

pagination

### Description

Hey, thanks for Elf. :heart: 

Using it in a project has been quite easy thus far. However, I'm stuck at implementing store pagination. The examples listed in the README do not use it, and the `ng`-app in the repository doesn't seem to work yet (the contacts page seems to be paginated, but traversing through the pages by clicking on them does nothing).

### Proposed solution

I'd love some extensive documentation on how to use it. The current docs include docstrings for the functions, but e.g. "set the current page" for `setCurrentPage` isn't terribly helpful.

### Alternatives considered

...

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
I'll update the Angular example asap.

**Comment by NetanelBasal** [comment]
The example has been fixed. Please open a discussion if you have additional questions.
