### ISSUE TITLE
update with duplicate ids

### ISSUE THREAD

**Issue by productivityindustries** [ngneat/elf#128]
### Which @ngneat/elf-* package(s) are the source of the bug?

store

### Is this a regression?

No

### Description

When performing a store.update with multiple entities (using setEntities, addEntities, ...), if two objects have the same ID the resulting store will have them both. Expected?

Obviously it's a bug from the caller, but still I would not expect a tainted store: even throwing an error is a better solution in this case IMO.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-xvpq7m?file=src/app/todos/state/todos.repository.ts

### Do you want to create a pull request?

No

**Comment by yackinn** [comment]
Thank you. I'll take care of it some time next week.

**Comment by productivityindustries** [comment]
Thank you!
Please note the same issue is present in akita, i filed a similar report there: https://github.com/datorama/akita/issues/796
