### ISSUE TITLE
Entities: get HashMap with unionEntities()

### ISSUE THREAD

**Issue by hakimio** [ngneat/elf#130]
### Which @ngneat/elf-* package(s) are relevant/releated to the feature request?

entities

### Description

Right now it doesn't seem to be possible to get a HashMap (`Record<string, Entity & EntityUI>`) when using `unionEntities()`. It only has an option for `idKey` and always returns `(Entity & EntityUI)[]`.

### Proposed solution

Another option to specify if we want to get a HashMap would be nice:
```ts
entityCombinationHashMap$ = store.combine({
    entities: store.pipe(selectAll()),
    UIEntities: store.pipe(selectEntities({ref: UIEntitiesRef}))
})
.pipe(
    unionEntities({
        idKey: 'myKey',
        hashMap: true
    })
);
```

### Alternatives considered

N/A

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
You're welcome to create a PR for the idKey. What's the use case for the `hashMap`?

**Comment by hakimio** [comment]
We already have `idKey`.
Use case for `hashMap`? The same as `selectEntities()` but with UI entities combined.

**Comment by NetanelBasal** [comment]
You're right :)

Yes, you can create a PR

**Comment by NetanelBasal** [comment]
See if it'll be better to use a different operator such as `unionEntitiesAsMap`

**Comment by hakimio** [comment]
Which approach do you personally prefer?

**Comment by NetanelBasal** [comment]
It depends on the code size

**Comment by NetanelBasal** [comment]
If it's two lines, I prefer your suggestion.
