### ISSUE TITLE
Type 'P_1' cannot be used to index type...

### ISSUE THREAD

**Issue by strigefleur** [ngneat/elf#14]
### Which @ngneat/elf-* package(s) are the source of the bug?

entities

### Is this a regression?

No

### Description

Created default repo with cli

```
const { state, config } = createState(
  withEntities<MyModelWithStringId>(),
  withActiveId(),
  withRequestsCache(),
  withRequestsStatus()
);
```

Trying to build then getting error.

### Please provide the exception or error you saw

```true
Error: node_modules/@ngneat/elf-entities/lib/entity.state.d.ts:33:130 - error TS2536: Type 'P_1' cannot be used to index type '{ [K_1 in EntitiesKey | IdsKey]: K_1 extends EntitiesKey ? Record<EntityType[IdKey], EntityType> : K_1 extends IdsKey ? EntityType[IdKey][] : never; }'.

33     props: { [P_1 in (Feature extends "" ? "entities" : `${Feature}Entities`) | (Feature extends "" ? "ids" : `${Feature}Ids`)]: { [K_1 in EntitiesKey | IdsKey]: K_1 extends EntitiesKey ? Record<EntityType[IdKey], EntityType> : K_1 extends IdsKey ? EntityType[IdKey][] : never; }[P_1]; };
```

### Please provide the environment you discovered this bug in

```true
VSCode 1.61.0
Windows_NT x64 10.0.22000

"@angular/core": "~12.2.9",
"rxjs": "7.3.0",
"typescript": "~4.3.5",

"@ngneat/elf": "^1.0.0-beta.4",
"@ngneat/elf-devtools": "^1.0.0-beta.2",
"@ngneat/elf-entities": "^1.0.0-beta.5",
"@ngneat/elf-pagination": "^1.0.0-beta.2",
"@ngneat/elf-persist-state": "^1.0.0-beta.2",
"@ngneat/elf-requests": "^1.0.0-beta.4",
"@ngneat/elf-state-history": "^1.0.0-beta.2",
```

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
Can you please show `MyModelWithStringId`?

**Comment by strigefleur** [comment]
Well, since I used the schematics command to generate repo, there are some more boilerplate:
(consider 'Sight' as MyModelWithStringId)
Will try to recreate clean repo as well in the nearest time.
```
const { state, config } = createState(
  withEntities<Sight>(),
  withActiveId(),
  withRequestsCache(),
  withRequestsStatus()
);
export const sightsStore = new Store({ name: 'sights', state, config });

@Injectable({ providedIn: 'root' })
export class SightsRepository {
  status$ = sightsStore.pipe(selectRequestStatus('sights'));
  activeSight$ = sightsStore.pipe(selectActiveEntity());
  sights$ = sightsStore.pipe(selectAll());

  setSights(sights: Sight[]) {
    sightsStore.update(updateRequestCache('sights'), setEntities(sights));
  }

  addSight(sight: Sight) {
    sightsStore.update(addEntities(sight));
  }

  updateSight(id: Sight['id'], sight: Partial<Sight>) {
    sightsStore.update(updateEntities(id, sight));
  }

  deleteSight(id: Sight['id']) {
    sightsStore.update(deleteEntities(id));
  }

  setActiveId(id: Sight['id']) {
    sightsStore.update(setActiveId(id));
  }

  updateRequestCache(state: CacheState) {
    sightsStore.update(updateRequestCache('sights'));
  }
}
```

**Comment by NetanelBasal** [comment]
Sure. Please let me know if you still see the issue when trying it on a clean repository.

**Comment by strigefleur** [comment]
Somehow I can't reproduce it on stackblitz, so here's what I exactly do:
1. ng new elf-error
2. cd elf-error
3. npx @ngneat/elf-cli install (selecting entities)
4. npm install @ngneat/elf-cli --save-dev
5. npm install @ngneat/elf-cli-ng --save-dev
6. add lines to package.json as noted in instructions
```
  "elf": {
    "cli": {
      "repoTemplate": "class",
      "repoLibrary": "state",
      "plugins": [
        "@ngneat/elf-cli-ng"
      ]
    }
  }
  ```
7. npx @ngneat/elf-cli repo (any suitable name, select entities)
8. ng serve (build is ok, no problems)
9. inject repo in component (I guess tree-shaking ignores it if you don't)
10. ng serve (aand here it is, the error)

The most unusual part is the fact that if I comment/uncomment the injected repo several times then under some circumstances it builds without error - but other times with error with exactly same lines of code.
Sorry, I still can't get into the reasons so that's the most of explanations I have atm.

https://user-images.githubusercontent.com/20131398/136689918-f72ac01e-0a15-413b-99ec-31fca8653814.mp4

**Comment by NetanelBasal** [comment]
Can you upload the code to a repo, please? I want to clone it and try it.

**Comment by strigefleur** [comment]
Sure, [here you are](https://github.com/strigefleur/elf-error).

**Comment by NetanelBasal** [comment]
Now I see it. I'll look into it. To make the compiler happy in the meantime, use `"skipLibCheck": true`.

**Comment by strigefleur** [comment]
Cool, thank you.
One more thing since you are already here: I was in the middle of migrating huge Angular project from NGXS to Akita when you announced Elf - what should I take into account choosing between both now (LTS, beta..)?

**Comment by NetanelBasal** [comment]
https://github.com/ngneat/elf/discussions/5#discussioncomment-1437641

**Comment by NetanelBasal** [comment]
Try v1.0.0-beta.6.
