### ISSUE TITLE
Support id update

### ISSUE THREAD

**Issue by DmitryEfimenko** [ngneat/elf#146]
### Which @ngneat/elf-* package(s) are the source of the bug?

entities

### Is this a regression?

No

### Description

After adding an entity optimistically and updating its id with the id from the server response, trying to update/delete this entity does not work

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/typescript-dqqpey?file=index.ts

### Please provide the exception or error you saw

```true
No exception. The action is simply not performed
```

### Please provide the environment you discovered this bug in

```true
Chrome 98
```

### Anything else?

I looked through the source code a bit, but could not spot where the issue is :(

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
Yes, It's because we currently don't support replacing the id. 

![image](https://user-images.githubusercontent.com/6745730/153150496-6d01f3c5-3bae-40d9-95d0-20c2e2df879b.png)

**Comment by NetanelBasal** [comment]
If I remember correctly, you added it to Akita. Would you like to create a PR?

**Comment by DmitryEfimenko** [comment]
yeah, I did. I would gladly create a PR. Do you mind pointing me to an approximate area where the change needs to be made?

**Comment by NetanelBasal** [comment]
updateEntities, upsertEntities.

See how you can make it reusable,

**Comment by NetanelBasal** [comment]
Note that, because it is not a typical case, I prefer to pass explicitly when needed - `updateEntitiy(id, {}, { idUpdated: true })`

**Comment by DmitryEfimenko** [comment]
what's the reason for that? Do you see performance degradation without it?

**Comment by NetanelBasal** [comment]
I'm not sure. Let's see the implementation without it first.
