### ISSUE TITLE
CLI creates repository incorrectly

### ISSUE THREAD

**Issue by EricPoul** [ngneat/elf#150]
### Which @ngneat/elf-* package(s) are the source of the bug?

CLI

### Is this a regression?

No

### Description

When I create a new repository with help of cli I get with the line where should be properly created state. 

There should be next:
```
const { state, config } = createState(withProps<TestProps>());
```
but have this:
```
const { state, config } = <>;
```
Even though all imports were added.

I faced this outcome when I tried to create states with different extensions: `withEntities`, `withRequestsCache` and so on.
Also if I remove `@ngneat/elf-cli-ng` plugin then the outcome be the same.

### Please provide the exception or error you saw

```true
$ npx @ngneat/elf-cli repo --dry-run
? Store name test
? Select features Props
? Where you like to put this repository? /../../test


CREATE /../../test.repository.ts

import { Store, createState, withProps } from '@ngneat/elf';

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface TestProps {
}

const { state, config } = <>;
export const store = new Store({ name: 'test', state, config });


NOTE: The "dryRun" flag means no changes were made.
```

### Please provide the environment you discovered this bug in

```true
Angular: 13.1.3
@ngneat/elf: 1.0.2,
@ngneat/elf-entities: 2.1.0,
@ngneat/elf-persist-state: 1.0.0,
@ngneat/elf-requests: 1.1.1,
@ngneat/elf-state-history: 1.0.1,
```

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
Are you using  `"typescript": "^4.3.5"`?

**Comment by NetanelBasal** [comment]
Can you please try using 4.3.5? The specs pass. I want to know if it's related to the version.

**Comment by EricPoul** [comment]
I've just tried with `"typescript": "^4.3.5"` and faced the same outcome.

**Comment by EricPoul** [comment]
```
$ tsc -v                                                                                                                                        127
Version 4.3.5
$ npx @ngneat/elf-cli repo --dry-run

? Store name test
? Select features Entities, Requests Cache
? Select CRUD operations Set
? idKey: id
? Where you like to put this repository? /path


CREATE /path/test.repository.ts

import { Store, createState } from '@ngneat/elf';
import { withEntities, selectAll, setEntities } from '@ngneat/elf-entities';
import { withRequestsCache } from '@ngneat/elf-requests';

export interface Test {
  id: number;
}

const { state, config } = <>;
export const store = new Store({ name: 'test', state, config });

export const test$ = store.pipe(selectAll());

export function setTest(test: Test[]) {
  store.update(setEntities(test));
}

NOTE: The "dryRun" flag means no changes were made.


```

**Comment by NetanelBasal** [comment]
I see it now. I'll get to it next week. Thanks for the report.

**Comment by NetanelBasal** [comment]
![image](https://user-images.githubusercontent.com/6745730/153725513-1f56e821-42ed-4369-9d10-a322069a561d.png)

**Comment by NetanelBasal** [comment]
It works when using typescript@4.3.5

**Comment by EricPoul** [comment]
It's strange because I don't have a global `tsc`. I checked ones more after deleting node_modules and installing new ones with specific version `"typescript": "4.3.5"`. After all, I have the same result.

**Comment by EricPoul** [comment]
@NetanelBasal I found where the problem! If I install `@ngneat/elf-cli` manually and not while using npx(as on screenshot) I will have the right output.
<img width="396" alt="image" src="https://user-images.githubusercontent.com/31760529/153726366-b914dfa4-e492-4d5f-80d4-fc6a4be27b5e.png">
