### ISSUE TITLE
updateEntitiesIds is not exported

### ISSUE THREAD

**Issue by DmitryEfimenko** [ngneat/elf#154]
### Which @ngneat/elf-* package(s) are the source of the bug?

entities

### Is this a regression?

No

### Description

In my previous PR I forgot to export the new `updateEntitiesIds` from the `index.ts`.

### Anything else?

I assumed that index.ts had something like `export * from './lib/update.mutation'`, but that's not the case. Functions are exported there individually. Is there a reason for that? Does that affect tree shaking?

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
done

**Comment by NetanelBasal** [comment]
No. I want to control what the library exposes as the public API.
