### ISSUE TITLE
Persist state is not releasing storage resources when unsubscribe is called

### ISSUE THREAD

**Issue by quadristan** [ngneat/elf#157]
### Which @ngneat/elf-* package(s) are the source of the bug?

persist-state

### Is this a regression?

No

### Description

Using `persistState` will subscribe to `getItem` of the storage. However, this subscription is never released.

### Please provide a link to a minimal reproduction of the bug

https://github.com/ngneat/elf/pull/156/files#diff-28051e207774bbfb19b1ff7bcaa02ae549a7322487b0325f31802c5b4008ae04R68

### Please provide the exception or error you saw

```true
Sending a simple `interval(1000)` on the storage of `getItem` will make any jest test suite complain about not well terminated test.
```

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
What is the use case for this? The getItem emits the initial item and that's it

**Comment by quadristan** [comment]
I want to be able to refresh the store when my underlaying storage emits an update notification. But i understand maybe we want to have some kind of `update` calls ?
If this is the case, then, i suggest doing a `take(1)` from the storage and unsubscribing it right after the store is initialized.

**Comment by NetanelBasal** [comment]
I still not sure I understand your case

**Comment by quadristan** [comment]
I am making a distributed app in two parts.
One part (main part) only will be able to push updates to the store while both parts can read the store.
I want to use the storage layer to push updates from the main part to the read-only part.
