### ISSUE TITLE
Add property to CLI config which allows creating store inside a class constructor.

### ISSUE THREAD

**Issue by EricPoul** [ngneat/elf#162]
### Which @ngneat/elf-* package(s) are relevant/releated to the feature request?

CLI

### Description

It would be nice to have the ability to create a repo(as a class) with a store created in the constructor. It would be useful when we want to create a component store or we want to set an initial value given from DI.

I'm about to create a pr and I am curious about your thoughts about solutions.

### Proposed solution

```ts
@Injectable({ providedIn: 'root' })
export class EntitiesRepository {
  readonly activeEntities$: Observable<Entity[]>;
  readonly activeEntity$: Observable<Entity | undefined>;
  readonly entities$: Observable<Entity[]>;
  ...
  
  private readonly store;

  constructor() {
    const { state, config } = createState(withEntities<Entity>(), withUIEntities<EntityUI>(), withActiveId(), withActiveIds());
    this.store = new Store({ name: 'entities', state, config });
    this.activeEntities$ = this.store.pipe(selectActiveEntities());
    this.activeEntity$ = this.store.pipe(selectActiveEntity());
    this.entities$ = this.store.pipe(selectAll());
    ...
  }

  setEntities(entities: Entity[]) {
    this.store.update(setEntities(entities));
  }
  
  ...
}
```

Or with a separate function for creating a store(this one may be better due to reducing space in the constructor filled by `createState` function after using a "prettier"). This variant is a little neater but has more complicated types.

```ts
@Injectable({ providedIn: 'root' })
export class EntitiesRepository {
  readonly activeEntities$: Observable<Entity[]>;
  readonly activeEntity$: Observable<Entity | undefined>;
  readonly entities$: Observable<Entity[]>;
  ...
  
 private readonly store: ReturnType<EntitiesRepository['getStore']>;

  constructor() {
    this.store = this.getStore();
    this.activeEntities$ = this.store.pipe(selectActiveEntities());
    this.activeEntity$ = this.store.pipe(selectActiveEntity());
    this.entities$ = this.store.pipe(selectAll());
    ...
  }

  setEntities(entities: Entity[]) {
    this.store.update(setEntities(entities));
  }
  
  ...
  
 private getStore(): Store<{ name: string, state: typeof state, config: typeof config }> {
    const { state, config } = createState(withEntities<Entity>(), withUIEntities<EntityUI>(), withActiveId(), withActiveIds());

    return new Store({ name: 'entities', entities, config });
  }
}
```

### Alternatives considered

-

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
What you prefer?

**Comment by EricPoul** [comment]
As we need to set observables to properties in the constructor I prefer the variant with a separate method for creating a store. Schematic will set these types so for users it shouldn't be a bother. Some people may use linter rules that require explicitly setting a type to the property and in the first variant, we can't get the type of the store until creating it.

Also, don't you mind mine adding `readonly` for all properties in the `class` repo?

**Comment by NetanelBasal** [comment]
To be honest, I don't believe in readonly :)

**Comment by NetanelBasal** [comment]
So let's go with the function.

**Comment by EricPoul** [comment]
I got about `readonly`😄, it's not that hard to manually add it.
