### ISSUE TITLE
freeze store in dev mode

### ISSUE THREAD

**Issue by DmitryEfimenko** [ngneat/elf#163]
### Which @ngneat/elf-* package(s) are relevant/releated to the feature request?

store

### Description

Akita has this awesome feature which prevents a lot of bugs: [freezing the store in dev mode](https://datorama.github.io/akita/docs/config/#production-mode)

This is to implement a similar feature for the elf.

### Proposed solution

it will be a matter of setting `__DEV__` variable just like [it's done in Akita](https://github.com/datorama/akita/blob/2aaf7e351672cf4d0d5c2e0783470241b2046428/packages/akita/src/lib/env.ts) and including the following code [here](https://github.com/ngneat/elf/blob/master/packages/store/src/lib/store.ts#L38):

```ts
const { deepFreeze } = this.getConfig();
if (__DEV__ && deepFreeze) {
  value = deepFreeze(value);
}
```

### Prod mode
* This could be a breaking change if we decide that the default behavior should require calling `enableElfProdMode()` for production mode.

* The alternative is to have elf act in prod mode by default and create a function `enableElfDevMode()`.

I honestly would prefer `enableElfProdMode()` even though this would make it a breaking change.

### Tree shaking
* We could include the [default implementation of the deepFreezeFn](https://github.com/datorama/akita/blob/2aaf7e351672cf4d0d5c2e0783470241b2046428/packages/akita/src/lib/deepFreeze.ts) to be bundled together with the `Store` just like Akita does it. This would increase the bundle size a bit.

* Alternatively, we could require a user to provide the `deepFreeze` function in the store configuration. This way it would be shaken away for these people who are not interested in this functionality:

   ```ts
   import { deepFreeze } from '@ngneat/elf';

   const { state, config } = createState(withProps<AuthProps>({ user: null }));
   const authStore = new Store({ state, name: 'auth', config, deepFreeze });
   ```

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
It would probably be better to add a global custom `preStoreUpdate` hook:

```ts
preStoreUpdate(newState) {
  return deepFreeze(newState)
}
```

**Comment by DmitryEfimenko** [comment]
Not sure where `preStoreUpdate` function comes from. We could introduce a global object: `elfHooks`:
```ts
export interface ElfHooks {
  preStoreUpdate?: <S>(newState: S, storeName: string) => S;
}

export const elfHooks: ElfHooks = {};
```
This way, the consumer could use it like so:
```ts
import { elfHooks } from '@ngneat/elf';

elfHooks.preStoreUpdate = (newState, storeName) => {
  return deepFreeze(newState);
};
```
Does that sound all right?

**Comment by NetanelBasal** [comment]
Yes, that's exactly what I meant.

**Comment by DmitryEfimenko** [comment]
I'm working on this feature and trying to make it ergonomic for the developer. One thing I'd like to achieve is to specify the type of the store so that the developer gets intellisense inside of the `preStoreUpdate` function.

However, I'm running into an error that I'm having a hard time understanding. Do you have an idea [what's happening here](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgKIBsYAkD2ODWAzsgN4CwAUMsgA5QQDKYO9AqjQCZyQD8AXMgA8DAHwAKEBADuTbhAEMANMkLN6AOTgBbeSrBRQAcwCUyALwjkDANyUAvpUoIcIVcgiZcBQgIzY8ROakdrYUjhRgAJ40KLKQQSTIMMDokFACqgYghsgh4QD0+chSABaRyBw4EMRgJcDE8Ck8lB7+3gB0dIxqEOxc8WbIEtJxuqOmFqSU1PRgAK5QIKRJKWkCAOSt67mhIUA)?

**Comment by NetanelBasal** [comment]
```ts
interface ElfHooks<State> {
  preStoreUpdate?: (prevState: State, newState: State, storeName: string) => State;
}

const elfHooks: ElfHooks<State> = {
  preStoreUpdate(state) {
    return { filter: 'elf' };
  }
};


type State = { filter: string };
```

**Comment by NetanelBasal** [comment]
How you access it in the store?

**Comment by DmitryEfimenko** [comment]
through `elfHooksRegistry`. When I said that we don't export it, I meant we don't export it to the public API. we can export the `const` and access it in the store

**Comment by DmitryEfimenko** [comment]
Please see the PR for details. Let me know if anything looks off. If not, I'll add docs
