### ISSUE TITLE
initializeAsPending has no check for request types specified by withRequestsStatus<T>

### ISSUE THREAD

**Issue by strigefleur** [ngneat/elf#169]
### Which @ngneat/elf-* package(s) are the source of the bug?

requests-status

### Is this a regression?

No

### Description

`initializeAsPending` accepts any input even if you set some custom types at `withRequestsStatus`.

So this example will give no error despite the fact `FooBarRequests` union contains no `todos` literal.

```
type FooBarRequests = 'foo' | 'bar';
withRequestsStatus<FooBarRequests>(
    initializeAsPending('todos')
)
```

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
`initializeAsPending` takes a `string | string[]`, it's not strictly typed.

**Comment by NetanelBasal** [comment]
Add a generic option - `initializeAsPending<Keys>`
