### ISSUE TITLE
Types issues after creating a store with createStore

### ISSUE THREAD

**Issue by EricPoul** [ngneat/elf#176]
### Which @ngneat/elf-* package(s) are the source of the bug?

store

### Is this a regression?

No

### Description

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/31760529/155297985-28d54ac7-3808-42a5-a384-922d46f2d604.png">

### Do you want to create a pull request?

No

**Comment by EricPoul** [comment]
The problem is in union type instead of concatenating types
<img width="477" alt="image" src="https://user-images.githubusercontent.com/31760529/155298749-6388d27e-29e1-431a-920f-05aea33f1e61.png">
<img width="452" alt="image" src="https://user-images.githubusercontent.com/31760529/155298785-1ab1122a-3f92-41b0-b9a3-aeaddfd01df8.png">

**Comment by NetanelBasal** [comment]
@DmitryEfimenko what's changed?

**Comment by DmitryEfimenko** [comment]
I can't reproduce the issue. Here's what I tried:
```ts
const store = createStore(
  { name: 'todo' },
  withEntities<Todo>(),
  withActiveId()
);
```
![image](https://user-images.githubusercontent.com/2098175/155380446-a8aaff7c-f7b9-4da7-b6f2-e0beef875c67.png)

@EricPoul Could you please show your store definition? Or better yet, come up with a small reproduction on StackBlitz.

**Comment by EricPoul** [comment]
The whole generated class
```ts
import { Injectable } from '@angular/core';
import { createStore, withProps } from '@ngneat/elf';
import {
  addEntities,
  deleteEntities,
  selectActiveEntities,
  selectActiveEntity,
  selectAll,
  setActiveId,
  setEntities,
  toggleActiveIds,
  updateEntities,
  withActiveId,
  withActiveIds,
  withEntities,
  withUIEntities,
} from '@ngneat/elf-entities';
import { withRequestsCache, withRequestsStatus } from '@ngneat/elf-requests';
import { Observable } from 'rxjs';

export interface TodoUI {
  id: number;
}

export interface Todo {
  id: number;
}

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface TodosProps {}

@Injectable({ providedIn: 'root' })
export class TodosRepository {
  activeTodos$: Observable<Todo[]>;
  activeTodo$: Observable<Todo | undefined>;
  todos$: Observable<Todo[]>;

  private readonly store;

  constructor() {
    this.store = this.createStore();
    this.todos$ = this.store.pipe(selectAll());
    this.activeTodo$ = this.store.pipe(selectActiveEntity());
    this.activeTodos$ = this.store.pipe(selectActiveEntities());
  }

  setTodos(todos: Todo[]) {
    this.store.update(setEntities(todos));
  }

  addTodo(todo: Todo) {
    this.store.update(addEntities(todo));
  }

  updateTodo(id: Todo['id'], todo: Partial<Todo>) {
    this.store.update(updateEntities(id, todo));
  }

  deleteTodo(id: Todo['id']) {
    this.store.update(deleteEntities(id));
  }

  setActiveId(id: Todo['id']) {
    this.store.update(setActiveId(id));
  }

  toggleActiveIds(ids: Array<Todo['id']>) {
    this.store.update(toggleActiveIds(ids));
  }

  private createStore(): typeof store {
    const store = createStore(
      { name: 'todos' },
      withProps<TodosProps>({}),
      withEntities<Todo>(),
      withUIEntities<TodoUI>(),
      withActiveId(),
      withActiveIds(),
      withRequestsCache<'todos'>(),
      withRequestsStatus<'todos'>(),
    );

    return store;
  }
}

```

**Comment by EricPoul** [comment]
https://stackblitz.com/edit/typescript-jaliv2

stackblitz doesn't show errors but if you hover over `store` you'll see a wrong type and `todos$` is `Observable<any>`

**Comment by NetanelBasal** [comment]
Works for me in elf repo:

<img width="706" alt="image" src="https://user-images.githubusercontent.com/6745730/155390623-6df9ffe2-07fb-4ac9-a277-0566fe0b48e4.png">

**Comment by NetanelBasal** [comment]
@EricPoul you're the only one that can check what's different. Try in elf repo and diff with your unworking version.

**Comment by DmitryEfimenko** [comment]
I wonder if the version of TypeScript that's set to evaluate your code in VsCode has to do with anything.
Or maybe node_modules need to be deleted and reinstalled?

**Comment by NetanelBasal** [comment]
@DmitryEfimenko Using the prev code works as expected:

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/6745730/155391737-c1b178ab-710e-4fa0-bcb2-3fdb902ec467.png">

**Comment by DmitryEfimenko** [comment]
exact same code in VsCode and in StackBlitz gives different results... hmm

I did go through all changes in my PR and made sure that I didn't modify any typing code. If there's an error, it's in the definition of [`createStore` function](https://github.com/ngneat/elf/blob/master/packages/store/src/lib/create-store.ts)

**Comment by NetanelBasal** [comment]
Try to play with it in the docs. Run yarn start:docs and modify it. You should see it on stacklitz locally.

**Comment by DmitryEfimenko** [comment]
the only difference between typing info there is:
```
createState<S extends PropsFactory<any, any>[]>
// vs
createStore<S extends [PropsFactory<any, any>, ...PropsFactory<any, any>[]]>
```
You see in the createStore the type is a bit different. It's that way to enforce at least one state definition. Could this be the issue?

**Comment by NetanelBasal** [comment]
I'm not sure. Check it locally.

**Comment by NetanelBasal** [comment]
It should be `  S extends PropsFactory<any, any>[]`

**Comment by NetanelBasal** [comment]
I didn't notice that change you did in the PR. I also not sure why you did this

**Comment by DmitryEfimenko** [comment]
to prevent [this](https://github.com/ngneat/elf/blob/master/packages/store/src/lib/create-store.spec.ts#L29-L30)

**Comment by NetanelBasal** [comment]
Let's first see if this is the real issue

**Comment by NetanelBasal** [comment]
Same

**Comment by DmitryEfimenko** [comment]
yeah, tried locally. This does not seem to be the issue

**Comment by NetanelBasal** [comment]
@DmitryEfimenko, please investigate what's wrong. If we don't find a solution, I will have to revert this change.

**Comment by NetanelBasal** [comment]
You can copy-paste the `Store` code to stackblitz and investigate

**Comment by EricPoul** [comment]
Once I did this for test it works. Maybe `Merge` type is an issue?
```ts
type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
    k: infer I
  ) => void
  ? I
  : never;
type Merge<State extends any[], Key extends PropertyKey> = UnionToIntersection<
  State[number][Key]
  >;

export function createStore<
  S extends PropsFactory<any, any>[]
>(storeConfig: StoreConfig, ...propsFactories: S): Store<{ name: string; state: Merge<S, 'props'>; config: Merge<S, 'config'> }> {
  const { state, config } = createState(...propsFactories);
  const { name } = storeConfig;

  return new Store({ name, state, config });
}
```

**Comment by NetanelBasal** [comment]
But it works with the prev version.

**Comment by DmitryEfimenko** [comment]
Are we OK with this fix? I don't understand it, but if it fixes the issue, I'd use it

**Comment by EricPoul** [comment]
It is strange. It works fine in the elf app examples but after I build store and link it to the my local app an error pops up

**Comment by NetanelBasal** [comment]
Something is different; you need to find what :). I'd check the `d.ts` file generation.

**Comment by EricPoul** [comment]
As far as I can see, TS can't infer `MERGE` a type when I'm using build version(like after installing a package) and says that it's **`one of`** `S` type passed to the `createStore` method. As I said above, we need manually write a type.
In `createState` you did `as { state: Merge<S, 'props'>; config: Merge<S, 'config'> }` and if we do the same in a store that it'' be work.

**Comment by DmitryEfimenko** [comment]
works for me! @EricPoul would you like to create this PR or would you like me to do this?
Since you've done majority of the research and understand the issue a bit better, I would not mind if you did it, but I'm OK to take on it as well. Please let me know

**Comment by EricPoul** [comment]
You’re welcome. I can get to it too but only tomorrow. I would wait for @NetanelBasal  answer.

**Comment by DmitryEfimenko** [comment]
@EricPoul, please give it a shot. I'm having trouble making it work. The generated type definitions after the build end up inferred for me. Maybe I'm updating things in the wrong places.

**Comment by NetanelBasal** [comment]
We're back to normal. When I have time, I'll investigate this behaviour. Thanks @EricPoul.
