### ISSUE TITLE
Support transactions

### ISSUE THREAD

**Issue by bifty** [ngneat/elf#187]
### Which @ngneat/elf-* package(s) are relevant/releated to the feature request?

store

### Description

When updating a store multiple times it would increase the performance  if these updates can be performed within an transaction.

This way the subscribers would noticed less and it would also have a visible optimization in the DevTools (less updates).

### Proposed solution

same behaviour as applyTransaction in akita.

### Alternatives considered

/

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
You can perform multiple updates using the update method:

```ts
store.update(
  setProp('foo', 1),
  updateEntities(),
  ...
)
```

**Comment by NetanelBasal** [comment]
There is also emitOnce function. Check out the docs.

**Comment by PEZO19** [comment]
@NetanelBasal Do transactions also play together with `elf-persist-state` even in async case? Use case: using React Native's AsyncStorage I'm afraid in-memory data and persisted data can go inconsistent in case of an unexpected termination. Is there a protection against that?

**Comment by NetanelBasal** [comment]
I think it's a rare case. No one also complains about it in Akita.

**Comment by PEZO19** [comment]
@NetanelBasal Thanks, this is good news! This is what blocks me though these days, however I don't see this issue addressed by anyone even in the wider community, maybe core database guys.
