### ISSUE TITLE
CLI 

### ISSUE THREAD

**Issue by KenGuggelmeyer** [ngneat/elf#190]
### Which @ngneat/elf-* package(s) are the source of the bug?

CLI

### Is this a regression?

No

### Description

Hi,

When I run the command 'npx @ngneat/elf-cli repo' I can't select a directory to put the repo in. 
I always get the following output:
`npx @ngneat/elf-cli repo
? Store name test
? Select features Props
? Where you like to put this repository?  
  No results...`

Steps I tried:
- installing the elf-cli globally 
- running the command in an elevated command prompt
- Hardcoding a repoLibrary (I also had to do this for the AKITA-CLI)
- Added elf.config.js with a hardcoded rootpath.

All of this gives me the same error. 

### Please provide the exception or error you saw

```true
npx @ngneat/elf-cli repo
? Store name test
? Select features Entities
? Select CRUD operations Set
? idKey: id
? Where you like to put this repository?
  No results...
```

### Please provide the environment you discovered this bug in

```true
Windows 11:
Package.json
{
  "name": "ngx.test.elf",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~13.2.0",
    "@angular/common": "~13.2.0",
    "@angular/compiler": "~13.2.0",
    "@angular/core": "~13.2.0",
    "@angular/forms": "~13.2.0",
    "@angular/platform-browser": "~13.2.0",
    "@angular/platform-browser-dynamic": "~13.2.0",
    "@angular/router": "~13.2.0",
    "@ng-icons/core": "^13.3.0",
    "@ng-icons/heroicons": "^13.3.0",
    "@ngneat/elf": "^1.5.0",
    "@ngneat/elf-cli-ng": "^1.0.0",
    "@ngneat/elf-devtools": "^1.2.0",
    "@ngneat/elf-entities": "^4.0.1",
    "@ngneat/elf-pagination": "^1.0.0",
    "@ngneat/elf-requests": "^1.1.2",
    "@ngneat/transloco": "^3.1.4",
    "moment": "^2.29.1",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.2.5",
    "@angular/cli": "~13.2.5",
    "@angular/compiler-cli": "~13.2.0",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "autoprefixer": "^10.4.2",
    "jasmine-core": "~4.0.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "postcss": "^8.4.7",
    "tailwindcss": "^3.0.23",
    "typescript": "~4.5.2"
  },
  "elf": {
    "cli": {
      "repoTemplate": "class",
      "inlineStoreInClass": true,
      "idKey": "_id",
      "repoLibrary": "state",
      "plugins": []
    }
  }
}
```

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
Maybe you have the same issue as https://github.com/ngneat/elf/issues/81?

**Comment by KenGuggelmeyer** [comment]
Yep. That was it. My folder name contains dots. After reading #81 I have to agree that only foldernames leading with a dot need to be disregarded. Folders containing a dot should not be ignored.

For my use case I tend to label the project folders with the DNS name. e.g.:
example.com
api.example.com
Because the project folder contains dots the 'no results ...' message is displayed.

For now I renamed the folder and it works.
