### ISSUE TITLE
Id of an Entity Interface must have name as "id" for it to work 

### ISSUE THREAD

**Issue by Randle-Lanre** [ngneat/elf#209]
### Which @ngneat/elf-* package(s) are the source of the bug?

entities

### Is this a regression?

Yes

### Description

cannot create an entity type with an interface id field named with a different name other than Id

for example 

```
export interface Product{
  productId: string,
  shortDescription :string,
  
}
```
`export const store = createStore({ name: 'product' }, withProps<NewsProps>({}), withEntities<Product>(), withActiveId(), withRequestsCache<'product'>(), withRequestsStatus<'product'>());`

if a user was making a call to backend API and the returned object has and Id named "productId" instead of "id"

NB: the error is thrown by `withEntities<Product>()`

### Please provide the exception or error you saw

```true
<html>TS2344: Type 'Product' does not satisfy the constraint '{ id: PropertyKey; }'.<br/>Property 'id' is missing in type 'Product' but required in type '{ id: PropertyKey; }'.
```

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
https://ngneat.github.io/elf/docs/features/entities/entities/#idkey

**Comment by NetanelBasal** [comment]
Reproduce on stackblitz, please
