### ISSUE TITLE
reset from propsFactory resets to initial value that passed into propsFactory

### ISSUE THREAD

**Issue by EricPoul** [ngneat/elf#238]
### Which @ngneat/elf-* package(s) are the source of the bug?

store

### Is this a regression?

Yes

### Description

IDK whether this is a bug but it's confusing that `reset${normalizedKey}` from `propsFactory` resets to an initial value that was passed to the `propsFactory` even if we set a different initial value when evoke `with${normalizedKey}`. As I understand, `reset${normalizedKey}` should respect an initial value passed to `with${normalizedKey}` primarily and if there is none then use the initial value that was passed to `propsFactory`.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/typescript-5svpfb

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
This works as expected. The `initialValue` is the one passed to `propsFactory`.

**Comment by NetanelBasal** [comment]
I don't think it's possible, even if we wanted to.

**Comment by NetanelBasal** [comment]
Ok, I think we can save the initial value in a closure and use it. You're welcome to create a PR.

**Comment by NetanelBasal** [comment]
I don't think it's going to work. The closure variable is shared with all `withPagination` calls.

**Comment by EricPoul** [comment]
You're right... I didn't think of it

**Comment by NetanelBasal** [comment]
You're welcome to try :)

**Comment by EricPoul** [comment]
I did something but it was the same as you warned me but in a different way. I guess I should admit that there's no way to know an initial value in `reset` that we passed into `with`. We did factory over propsFactory to pass extra type and I think we should make factory over propsFactory if we want to reset to the proper initial value.

**Comment by NetanelBasal** [comment]
Yep. I'm closing the issue. Thanks for trying :)
