### ISSUE TITLE
Add Entity Actions to listen for any store action

### ISSUE THREAD

**Issue by 5im0n** [ngneat/elf#247]
### Description

Add entity action as they are in Akita: https://datorama.github.io/akita/docs/entities/query-entity/#entity-actions

### Proposed solution

```ts

import { selectEntityAction, EntityActions  } from '@ngneat/elf-entities';

// Listen for a specific action
store.query(selectEntityAction(EntityActions.Set)).subscribe(newIds => {})
store.query(selectEntityAction(EntityActions.Add)).subscribe(addedIds => {});
store.query(selectEntityAction(EntityActions.Update)).subscribe(updatedIds => {});
store.query(selectEntityAction(EntityActions.Remove)).subscribe(removedIds => {});

// listen for a subset of actions
store.query(selectEntityAction([EntityActions.Add, EntityActions.Remove])).subscribe(action => {});

// listen for all actions
store.query(selectEntityAction()).subscribe(action => {});
```

### Alternatives considered

🤔

**Comment by 5im0n** [comment]
@NetanelBasal, what do you suggest to implements this new feature ?

In Akita an [observable](https://github.com/datorama/akita/blob/76980498e1d285df8a05826be8f6bc0da0e82dba/packages/akita/src/lib/entityStore.ts#L64) is used to propagate entities event.

However in Elf every mutation functions is a pure function.

**Comment by NetanelBasal** [comment]
Yes. We can exclude the core entity mutations for this benefit and emit the action in each.

**Comment by NetanelBasal** [comment]
```ts
import { ofType } from '@ngneat/elf';
import { EntityActions } from '@ngneat/elf-entites';

store.actions$.pipe(ofType(EntityActions.Add)).subscribe()
```

**Comment by doerig** [comment]
hi, is there any progress with this issue? it sounds like a very useful addition

**Comment by NetanelBasal** [comment]
https://ngneat.github.io/elf/docs/miscellaneous/entity-events
