### ISSUE TITLE
Elf is failing with an unterminated template literal in lib/props-array-factory.d.ts

### ISSUE THREAD

**Issue by adamglang** [ngneat/elf#263]
### Which @ngneat/elf-* package(s) are the source of the bug?

store

### Is this a regression?

No

### Description

I added the cli (v3.0.0) and used it to install the following

    "@ngneat/effects-ng": "^2.0.0",
    "@ngneat/elf": "^2.0.0",
    "@ngneat/elf-persist-state": "^1.1.1",

Simply attempting to import the following

`import { createStore, withProps } from '@ngneat/elf';`

results in the entire app breaking with "node_modules/@ngneat/elf/lib/props-array-factory.d.ts:17:1 - error TS1160: Unterminated template literal."

Inspecting the offending file produces the same linting errors

### Please provide the exception or error you saw

```true
node_modules/@ngneat/elf/lib/props-array-factory.d.ts:17:1 - error TS1160: Unterminated template literal.
```

### Please provide the environment you discovered this bug in

```true
angular: 11.2.0
typescript: 4.0.5
```

### Do you want to create a pull request?

No

**Comment by adamglang** [comment]
Well I updated ts to 4.6.3 and it fixed the problem. Not sure if you want to close this or not - I will leave it to you

**Comment by NetanelBasal** [comment]
Thanks, I'll close it for now.
