### ISSUE TITLE
Strange behavior with custom id properties when using Entities and UIEntities together.

### ISSUE THREAD

**Issue by WillooWisp** [ngneat/elf#269]
### Which @ngneat/elf-* package(s) are the source of the bug?

entities

### Is this a regression?

Yes

### Description

Enitities together with UIEntities and custom id property does not seem to map / union correctly. Changing to standard id property with no custom idKey configuration works however. Below all NodeUI UIEntities are initialized with true, but binding a list of elements to $nodes and rendering something different depending on isFavorite or not does not render all elements as favorites.

```
interface Node {
	nodeId: number;
	name: string;
}

interface NodeUI {
	nodeId: Node['nodeId'];
	isFavorite: boolean;
}

const nodesStore = createStore(
	{ name: 'nodes' },
	withEntities<Node, 'nodeId'>({ idKey: 'nodeId' }),
	withUIEntities<NodeUI, 'nodeId'>({ idKey: 'nodeId' }),
	withRequestsStatus(),
	withRequestsCache<'nodes'>()
);

nodes$ = nodesStore
    .combine({
        entities: nodesStore.pipe(selectAllEntities()),
        UIEntities: nodesStore.pipe(selectEntities({ ref: UIEntitiesRef })),
    })
    .pipe(
        unionEntities(),
        shareReplay({ refCount: true })
    );

setNodes(nodes: Node[]) {
    const uiNodes = nodes
        .map<NodeUI>(({ nodeId }) => ({ nodeId, isFavorite: true }));
    nodesStore.update(
        updateRequestCache('nodes'),
        addEntities(nodes),
        addEntities(uiNodes, { ref: UIEntitiesRef }),
        updateRequestStatus('nodes', 'success'));
}
```

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
Please provide a simple stackblitz example.

**Comment by WillooWisp** [comment]
@NetanelBasal I did not get stackblitz to work, just hang on compiling application, but used codesandbox instead. Not sure this illustrates the same problem, but the behavior does not seem correct when using a custom id property on entity together with ui entity, since it should map them together with true as favorite, which it does if changing to default id property instead of nodeId as id property.

https://codesandbox.io/s/quiet-star-56m5ii

**Comment by NetanelBasal** [comment]
`unionEntities('nodeId')`

**Comment by NetanelBasal** [comment]
I've updated the docs.
