### ISSUE TITLE
Set initial value on the propsFactory in the repo constructor

### ISSUE THREAD

**Issue by EricPoul** [ngneat/elf#274]
### Which @ngneat/elf-* package(s) are relevant/releated to the feature request?

store

### Description

There's the case in Angular when I want to set the initial value in the construction after getting some options token. Yes, we have `withProps` method but as said in this issue(it works as expected) https://github.com/ngneat/elf/issues/238 while resetting we'll get an initial value passed to the `propsFactory`. It can work if we'll create a class method that will create a props factory and we'll evoke it before creating a store but it's too complicated and demands setting props to the class property to be able to be seen.

### Proposed solution

I see two ways of doing it.
1. `withProps` overwrite the initial value(I'd prefer this one); As we create separate propsFactory for each store that it will work fine ;
2. create one more method in each props factory `setPropsInitialValue`;

If we create `propsFacroty` once for multiple usages it'll change an initial value for all who're using this props factory but with the second variant, you just can hide and not export `setPropsInitialValue`.

### Alternatives considered

-

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
Can you please add code examples? I don't think I understood.

**Comment by EricPoul** [comment]
In this case, as for now, I can set a filters in the constructor but on resetting them I'll reset them to the value that is inside of `filtersPropsFactory` but I want it to be reset to the value I got from DI.
```ts
const { withFilters } = filtersPropsFactory();

class {
  constructor(@inject(DEFAULT_FILTERS) filters: {}) {
     this.store = this.createStore(filters);
  }
  
  private createStore(filters: {}): typeof store {
    const store = createStore(
      { name: 'name' },
      withFilters(filters),
    );

    return store;
  }
}
```
to fix this either `withFilters` should replace an initial value of filtersPropsFactory or add new method
```ts
const { withFilters, setFiltersInitialValue } = filtersPropsFactory();

class {
  constructor(@inject(DEFAULT_FILTERS) filters: {}) {
     setFiltersInitialValue(filters);
     this.store = this.createStore();
  }
  
  private createStore(): typeof store {
    const store = createStore(
      { name: 'name' },
      withFilters(),
    );

    return store;
  }
}
```

**Comment by EricPoul** [comment]
I guess, we can make something like this too:
```ts
const { withVersion } = propsFactory('version', { initialValue: 1 });

// you can not pass an initial value to the `withVersion` if you passed to the `propsFactory`
withVersion();
```
```ts
const { withVersion } = propsFactory<T>('version');

// you must pass an initial value to the `withVersion` if you didn't pass to the `propsFactory`
withVersion(1);
```
