### ISSUE TITLE
Enable HMR with Angular

### ISSUE THREAD

**Issue by feitzi** [ngneat/elf#291]
How can we archive Hot Module Replacement with Elf and Angular?

With Akita it was possible as described [here](https://opensource.salesforce.com/akita/docs/angular/hmr/)

**Comment by hakimio** [comment]
It just works for me without any workarounds. Did you experience any issues?

**Comment by feitzi** [comment]
Thank you, that is the trick. F you create the elf store outside an angular service, then HMR works as desired
