### ISSUE TITLE
it expect yarn be installed!

### ISSUE THREAD

**Issue by mhamri** [ngneat/elf#295]
### Which @ngneat/elf-* package(s) are the source of the bug?

CLI

### Is this a regression?

No

### Description

i'm following the doc to install elf. it fails on installation and expect yarn be installed

```
❯ npx @ngneat/elf-cli install

Need to install the following packages:
  @ngneat/elf-cli
Ok to proceed? (y) y
    Error: Command failed with exit code 1: yarn --version
    'yarn' is not recognized as an internal or external command,
    operable program or batch file.
```

### Please provide the exception or error you saw

```true
'yarn' is not recognized as an internal or external command,
```

### Please provide the environment you discovered this bug in

```true
windows 11
powershell core 7.3
npm 8.11.0
node 16.15.1
```

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
It seems that you're working with yarn in your project. Is this assumption wrong?

**Comment by mhamri** [comment]
no, I don't have any yarn package. but to my surprise when I wanted to reproduce it today it worked just fine, I'm closing it for now, thank you!

**Comment by A-So-Nya** [comment]
It seems to break this way if you're not in the root folder of your project, i guees it should either give error that it should be executed from the root or detect package manager correctly from subfolders too.
