### ISSUE TITLE
There is a typo in documentation related to Entities queries.

### ISSUE THREAD

**Issue by lexeek** [ngneat/elf#300]
### Which @ngneat/elf-* package(s) are the source of the bug?

entities

### Is this a regression?

No

### Description

I've just noticed that documentation has a mistake about how queries must be used. I suppose that there should be executing of `query` method instead of `pipe`. I've also tried and query works.

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/1452043/180102420-9fdef267-334f-48ea-bd8d-10ab0c8b89eb.png">

### Please provide a link to a minimal reproduction of the bug

https://ngneat.github.io/elf/docs/features/entities/entities#getentitiescount

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
Thanks
