### ISSUE TITLE
[WIP] - Add Async Data Sources

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/elf#306]
### Description

Deprecate `withRequestsStatus`, `withCacheStatus`, and `createRequestDataSource` in favor of a combined feature - `Async Data Sources`.

## createAsyncDataSource

```ts
import { withAsyncDataSources, createAsyncDataSource } from '@ngneat/elf-async-data-source';

const store = createStore(
  { name: 'todos' },
  withEntities<Todo>(),
  withAsyncDataSources()
);

const todosDataSource = createAsyncDataSource({
  store,
  data$: store.pipe(selectAllEntities()),
  key: 'todos',
});

export interface AsyncDataSource {
  reqCount: number;
  //  The latest returned result
  data: T;
  // The cache value
  cache: 'partial' | 'full' | 'none';
  // When true, indicates that the query is currently fetching, but might have data from an earlier request.
  // This will be true for both the first request fired off, as well as subsequent requests.
  isFetching: boolean;
  // When true, indicates that the query is currently loading for the first time, and has no data yet.
  // This will be true for the first request fired off, but not for subsequent requests.
  isLoading: boolean;
  // When true, indicates that the query has data from a successful request
  isSuccess: boolean;
  // When true, indicates that the query is in an error state.
  isError: boolean;
  // When true, indicates that the query has not started yet.
  isUninitialized: boolean;
  // The error result if present.
  error: any;
}

todosDataSource.result$.subscribe((value) => {
  // value type is AsyncDataSource
});

function getTodos() {
  return timer(1000).pipe(
    map(() => [createTodo(1)]),
    tap((todos) =>
      store.update(setEntities(todos), todosDataSource.setSuccess())
    ),
    todosDataSource.track()
  );
}

```

### The `track` operator is responsible for three things:
- Update the request status
- Skip while the request is pending ( prevent concurrent requests )
- Skip while it cached

You can alter the cache behavior by:

```ts
todosDataSource.track({ skipCache: true })
todosDataSource.track({ skipWhileCacheIs: 'full' })

todosDataSource.setSuccess({ cache: 'partial' })
```

You can alter the default values:
```ts
const todosDataSource = createAsyncDataSource({
  store,
  data$: store.pipe(selectAllEntities()),
  key: 'todos',
  defaults: {
     isLoading: true
  }
});
```

## createDynamicAsyncDataSource
```ts
import { createDynamicAsyncDataSource, withAsyncDataSources } from '@ngneat/elf-async-data-source';

const store = createStore(
  { name: 'foo' },
  withEntities<Todo>(),
  withAsyncDataSources()
);

const todoDataSource = createDynamicAsyncDataSource({
  store,
  data$: (id) => store.pipe(selectEntity(id)),
});

todoDataSource.result$(1).subscribe((v) => {
  console.debug(v);
});

function getTodo(id: number) {
  return timer(1000).pipe(
    map(() => createTodo(id)),
    tap((todo) =>
      store.update(addEntities(todo), todoDataSource.setSuccess({ key: id }))
    ),
    todoDataSource.track({ key: id })
  );
}

```

### Alternatives considered

Nope.

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
@DmitryEfimenko @EricPoul would love to get your feedback here.

**Comment by EricPoul** [comment]
The idea is nice. I'd rather have not deprecated `withRequestsStatus` to use it for separate API call that belongs to the same repo as entities. 
For example, I have an API call to export my table data(entities) and need to show an independent loader. In this case, adding one new key to the `withRequestsStatus` is so convenient.

**Comment by NetanelBasal** [comment]
Are you talking about POST/PUT requests that don't update the store?

**Comment by EricPoul** [comment]
Yes, some requests that only update the state of its own loading

**Comment by NetanelBasal** [comment]
And you put it in the store because you need it in different components.

**Comment by EricPoul** [comment]
Not always. But I can use effects and in this case, the component doesn't know about API call and its state but can have access to the repo queries where the state of loading can be.

**Comment by EricPoul** [comment]
What if we had something like this:
```ts
// Yeah, name createAsyncRequests is odd)
const storeDataSources = createAsyncRequests<'todos' | 'todo'>();

// can be passed data source
storeDataSources.add('todos', {
  store,
  data$: store.pipe(selectAllEntities()),
})

storeDataSources.get('todos').track();

storeDataSources.get('todos').subscribe();

// can be passed dynamic data source
storeDataSources.add('todo', {
  store,
  data$: (id) => store.pipe(selectEntity(id)),
})

storeDataSources.get('todo').track();

storeDataSources.get('todo').subscribe();

// can be passed nothing
storeDataSources.add('export')

storeDataSources.get('export').track();

storeDataSources.get('export').subscribe();
```

**Comment by NetanelBasal** [comment]
What is the different from my approach?

**Comment by EricPoul** [comment]
we can deprecate `withRequestsStatus`, `withCacheStatus`, and `createRequestDataSource`

**Comment by EricPoul** [comment]
It can cover request statuses without sources

**Comment by EricPoul** [comment]
In general, I like your approach

**Comment by DmitryEfimenko** [comment]
I'd like to suggest an improvement for the `AsyncDataSource` data structure. The states of the data: `notAsked`, `loading`, `success`, and `error` are all mutually exclusive. The current data structure does not reflect that. As a result, consuming this data structure won't be optimal. For example, TypeScript won't yell at you when you write something like:
```ts
todosDataSource.result$.subscribe((result) => {
  // result type is AsyncDataSource
  if (result.isSuccess) {
    console.log(result.error)
  }
});
```
The `result.error` will always be `undefined` in this situation. This is an impossible situation, but TS does not tell you about it.
I suggest looking into [`RemoteData`](https://github.com/DmitryEfimenko/ngspot/tree/main/packages/remote-data) data structure. I wrote a [blog post](https://medium.com/@dmitrief/have-a-day-at-the-spa-working-on-your-spa-with-remote-data-2fa7bfb83ed3) about it recently.

Also, I don't see much value in `isFetching` property. `isLoading` should be enough. If you a look at the [`LoadingState`](https://github.com/DmitryEfimenko/ngspot/blob/main/packages/remote-data/src/lib/model.ts#L15-L19) of RemoteData, you'll see that it supports the use-case of keeping the "previous value" while the new data is loading. I can't think of any other use-case that would need to be supported.

**Comment by EricPoul** [comment]
@DmitryEfimenko I agree, it makes sense

**Comment by NetanelBasal** [comment]
@DmitryEfimenko I took the `state` from RTK-query. You can [read](https://redux-toolkit.js.org/rtk-query/usage/queries#frequently-used-query-hook-return-values) about `isLoading` vs. `isFetching`.

I also have a [library](https://github.com/ngneat/loadoff) for that which does the same. It's different here because the source is a selector from the store and not the HTTP data.

**Comment by NetanelBasal** [comment]
Moreover, I don't see why typescript should yell in your example. `result.error` will return `null`. It doesn't make sense to prevent accessing the value.

**Comment by DmitryEfimenko** [comment]
@NetanelBasal I've read the description. Thanks for the link. I still don't see much use in it. Can't think of a scenario that would be covered by the `isLoading` and `isFetching` and would not be covered by `RemoteData`. Maybe I'm wrong. It'd be good to see an example of such scenario in that case.

As for the my example, the way I see it is that if the state of the remote data is "success", then `error` property is irrelevant. It should not be in the context.

**Comment by NetanelBasal** [comment]
I do not see it as an issue. I am taking inspiration from libraries like react-query and RTK.
