### ISSUE TITLE
jest tests fail after upgrading @ngneat/elf-entities 4.3.1 -> 4.4.1

### ISSUE THREAD

**Issue by atsjo** [ngneat/elf#316]
### Which @ngneat/elf-* package(s) are the source of the bug?

entities

### Is this a regression?

Yes

### Description

jest tests fail after upgrading from 4.3.1 -> 4.4.1

### Please provide the exception or error you saw

```true
SyntaxError: Cannot use import statement outside a module

      2 | import { crc32, truncate } from '../utils';
      3 | import { createStore } from '@ngneat/elf';
    > 4 | import { addEntitiesFifo, withEntities } from '@ngneat/elf-entities';
        | ^
```

### Please provide the environment you discovered this bug in

```true
jest tests in nx angular project on windows (jest 27). working fine if downgrading to enitities 4.3.1
```

### Do you want to create a pull request?

No

**Comment by ThomasBurleson** [comment]
In my `jest.config.ts` I updated the *transformIgnorePatterns* to ignore elf packages:

```ts
  transform: {
    '^.+\\.(ts|mjs|js|html)$': 'jest-preset-angular',
  },
  transformIgnorePatterns: [`<rootDir>/node_modules/(?!@angular|@ngneat|array-move|lodash-es)`],
```

**Comment by NetanelBasal** [comment]
See if this article helps to understand the issue:

https://bobbyhadz.com/blog/typescript-jest-cannot-use-import-statement-outside-module

**Comment by atsjo** [comment]
This article above suggests the problem is that typescript is not transforming the files from typescript... I use standard jest setup from nx, and know there is problems using esm modukes. In 4.3.1 you published both esm and commonjs module in the package, allowing jest to pick commonjs. Now in 4.4.x you only publish esm module format (which uses import instead of require). The problem can be fixed by overriding som config, so jest will transform the esm code to commonjs for this package, but I was hoping for a more elegant solution, not requiring custom config for these packages...

**Comment by NetanelBasal** [comment]
I will check what's changed in Nx build

**Comment by atsjo** [comment]
I would think either publishing both formats as before, or publishing only esm but using mjs as file extension would fix the problem, as there is an exception for *.mjs already in transformIgnorePatterns: ['node_modules/(?!.*\\.mjs$)']

**Comment by NetanelBasal** [comment]
@atsjo @cyr-x check the latest versions of both, please.

**Comment by atsjo** [comment]
working fine now, I use both packages:-)
