### ISSUE TITLE
Error: require() of ES Module

### ISSUE THREAD

**Issue by bmayen** [ngneat/elf#319]
### Which @ngneat/elf-* package(s) are the source of the bug?

state-history, Don't known / other

### Is this a regression?

Yes

### Description

Attempting to run CLI with state history plugin:

```
Error: require() of ES Module node_modules/@ngneat/elf-state-history/index.js from
    node_modules/@ngneat/elf-cli/lib/commands/repo.js not supported.
    Instead change the require of index.js in
    node_modules/@ngneat/elf-cli/lib/commands/repo.js to a dynamic import() which is
    available in all CommonJS modules.
    Code: ERR_REQUIRE_ESM
```

Is this related to https://github.com/ngneat/elf/issues/316? This was happening with entities plugin until I upgraded to latest patch, then it started happening for state history plugin once that was resolved. Not sure if other modules are affected as well.

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
Does it happen when you run the application?

**Comment by bmayen** [comment]
I can compile and run an app with `import {stateHistory} from '@ngneat/elf-state-history'`

**Comment by bmayen** [comment]
I had this in the list of Elf's package.json plugins config. If I remove that and add the plugin manually, it works.

**Comment by NetanelBasal** [comment]
can you explain how to reproduce, please?

**Comment by bmayen** [comment]
In package.json I had "@ngneat/elf-state-history" as one of the plugins, like:
```
      "plugins": [
        ...,
        "@ngneat/elf-state-history"
      ]
```
Then, running `npx @ngneat/elf-cli repo` triggers that error. If I remove state history from the plugins array in the config, it works as expected.

**Comment by NetanelBasal** [comment]
I'm not sure why it's there. You can remove it.
