### ISSUE TITLE
Documentation Examples Broken

### ISSUE THREAD

**Issue by ronnyek** [ngneat/elf#353]
### Which @ngneat/elf-* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Loading documentation where stackblitz previews are mostly seem to not ever load. I suspected it could be because of the screen realestate afforded to the documentation. I dont see anyway to just open he example on stackblitz other than grabbing the preview url, but most never succeed in loading.

### Please provide a link to a minimal reproduction of the bug

https://ngneat.github.io/elf/docs/features/requests/requests-status

### Please provide the exception or error you saw

```true
editors load, and show code that seems to be valid, but the preview pane never shows anything for most examples. I don't know if there is a way to change settings on the embedded view, but if its possible... it'd be nice to click link and be able to open it in stackblitz directly.
```

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
It works for me. Can you check again?
