### ISSUE TITLE
Make `emitOnce` be stackable to use 2 child `emitOnce` inside parent `emitOnce`

### ISSUE THREAD

**Issue by EricPoul** [ngneat/elf#361]
### Which @ngneat/elf-* package(s) are relevant/releated to the feature request?

store

### Description

If a store is quite complex you can have 2 methods of store updating with `emitOnce` inside and in the some moment you want to call these methods together but still have one emission of the store.

```ts
function updateOne() {
  emitOnce(() => {
    authStore.update((state) => ({
      ...state,
      user: { id: 'foo' },
    }));
    authStore.update((state) => ({
      ...state,
      user: { id: 'foo2' },
    }));
  });
}

function updateTwo() {
  emitOnce(() => {
    authStore.update((state) => ({
      ...state,
      user: { id: 'bar' },
    }));
    authStore.update((state) => ({
      ...state,
      user: { id: 'bar2' },
    }));
  });
}

function updateThree() {
  emitOnce(() => {
    updateOne();
    updateTwo();
  });
}

updateThree();
```

With the current implementation, we'll see two emissions 
![image](https://user-images.githubusercontent.com/31760529/197773948-363e2a11-844d-4489-a905-4e52ce9d441f.png)

### Proposed solution

```ts
export const batchInProgress = new BehaviorSubject<boolean>(false);
export const batchDone$ = batchInProgress.asObservable().pipe(
  filter((inProgress) => !inProgress),
  take(1)
);

export function emitOnce<T>(cb: () => T) {
  if (!batchInProgress.getValue()) {
    batchInProgress.next(true);
    const value = cb();
    batchInProgress.next(false);

    return value;
  }

  return cb();
}
```

### Alternatives considered

-

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
Why not remove the emitOnce from the methods and use it only in updateThree?

**Comment by EricPoul** [comment]
first two methods could be called individually

**Comment by NetanelBasal** [comment]
Let's see a PR :)
