### ISSUE TITLE
Request: Upgrade notes

### ISSUE THREAD

**Issue by JorisDebonnet** [ngneat/elf#366]
I have been away from a project for a while, and today noticed that there is a 2.x release for Elf. Great! But I cannot find _anywhere_ whether there are any backwards incompatible changes. 

So my request is simply: could we start a changelog or upgrades notes or anything like that, to help users figure out whether they should be afraid of upgrading to a next major version, and perhaps also to mention new features in new versions?

**Comment by NetanelBasal** [comment]
https://github.com/ngneat/elf#change-logs

**Comment by JorisDebonnet** [comment]
> https://github.com/ngneat/elf#change-logs

Oh dear. I scrolled over that section multiple times, but I guess I did not read the section title. I thought they were just links to repositories. Maybe we can just add a single sentence under that title, for people who like me who tend to overlook titles sometimes?.. ☺️

**Comment by NetanelBasal** [comment]
What would you write?

**Comment by JorisDebonnet** [comment]
> What would you write?

How about "## 🗒️ Review the Change Logs" (see #367)?
