### ISSUE TITLE
Create registerPreStateInit hook

### ISSUE THREAD

**Issue by ivalexandr** [ngneat/elf#382]
### Discussed in https://github.com/ngneat/elf/discussions/381

<div type='discussions-op-text'>

<sup>Originally posted by **ivalexandr** November 19, 2022</sup>
Hello.  Why does the documentaion say that state in Elf is immutable? After all, we can change it without calling `update` method. 
Can we change this behavior and somehow protect from mutations the object obtained from the store?</div>

**Comment by NetanelBasal** [comment]
Add a new `registerPreStoreInit` hook that takes the provided initial state and returns it.

```ts
import { elfHooks, deepFreeze } from '@ngneat/elf';

if (!environment.production) {
  elfHooks. registerPreStoreInit((initialState, storeName) => {
    return deepFreeze(initialState);
  });
}
```

**Comment by NetanelBasal** [comment]
@ivalexandr, you're welcome to create a PR. It should be straightforward.
