### ISSUE TITLE
Search results in docs site redirects to 404 pages

### ISSUE THREAD

**Issue by mariojsnunes** [ngneat/elf#387]
### Which @ngneat/elf-* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

For example, if we click on search history:
![image](https://user-images.githubusercontent.com/8073622/203555948-d04a5ec3-9b68-4fc2-bacb-59c0a2d1792b.png)
We get this:
![image](https://user-images.githubusercontent.com/8073622/203556029-4271590b-f9d9-47f5-b30d-9bd7f427417d.png)

In this case, removing the last /history from the url works.

But for an url like .../entities/entities it should be .../entities-management/entities instead.

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
@shaharkazaz

**Comment by shaharkazaz** [comment]
@NetanelBasal @mariojsnunes I'll take a look

**Comment by NetanelBasal** [comment]
@mariojsnunes should be ok now, can you check, please?

**Comment by mariojsnunes** [comment]
Looks good, haven't found any issues again!
