### ISSUE TITLE
trackRequestResult - staleTime not working when request error

### ISSUE THREAD

**Issue by Benny739** [ngneat/elf#397]
### Which @ngneat/elf-* package(s) are the source of the bug?

requests-cache

### Is this a regression?

No

### Description

I observed that staleTime in the trackRequestResult cache is never reloading the data when an error status happened.
The error handler is not setting the staleTime property.

Maybe it would make sense to use an errorStaleTime property to have the option to reload errored requests more often.

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
If you want a retry on error, you can use the retry operator from RX

**Comment by Benny739** [comment]
My bad, the observable never got refired because it was in an error state.
What do you think about adding a catchError in the trackRequestResult stream, that errors do not kill the stream?

**Comment by NetanelBasal** [comment]
I don't know if everyone wants it. You can easily add one line operator:
https://netbasal.com/repeat-and-retry-http-requests-using-rxjs-423c1996fb65

**Comment by Benny739** [comment]
Right now errored requests will never expire and also skipCache will not retry these requests. They are cached forever, because the stream is in an error state.
I tried to write a test but couldn't find a way to put the stream in an error state without the test ending because I throw an error.

**Comment by Benny739** [comment]
The problem was my implementation with effects. 

```
   ofType(loadData),
      switchMap(() =>
        this.routerRepository.selectParams(['param1', 'param2']).pipe(first())
      ),
      switchMap(([param1, param2]) =>
        this.apiService.loadData(param1, param2)
      )
```

When apiService returned an HttpError the whole stream went in an error state and never fired again
