### ISSUE TITLE
trackRequestResult - when reloading data old state should be emitted immediately

### ISSUE THREAD

**Issue by Benny739** [ngneat/elf#398]
### Description

When trackRequestResult reloads data (either because of staleTime oder skipCache) the last data should be emitted immediately with isLoading: true. This way we can show the old data and then refresh the view once updated data arrives.

### Proposed solution

Emit last state immediately with isLoading:true by default.

### Alternatives considered

Make emitting last cache value optional when cache expired (or data is always reloaded)

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
Let's see PR :)

**Comment by NetanelBasal** [comment]
It should be fine in the latest version
