### ISSUE TITLE
UIEntities unionEntities() doesn't work with custom idKey provided

### ISSUE THREAD

**Issue by Exslims** [ngneat/elf#425]
### Which @ngneat/elf-* package(s) are the source of the bug?

store, entities

### Is this a regression?

Yes

### Description

Hey! 
If I provide custom idKey I can select UI entity data as expected, but combine with unionEntities() seems not working. 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/mvwxfe?file=index.ts

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
you need to pass the idKey

**Comment by Exslims** [comment]
@NetanelBasal Hi! What do you meant? I did it on stackblitz
```
const todosStore = createStore(
  { name: 'todos' },
  withEntities<Todo, 'newId'>({idKey: 'newId'}),
  withUIEntities<TodoUI, 'newId'>({idKey: 'newId'})
);
```

**Comment by NetanelBasal** [comment]
```
  .pipe(unionEntities('newId')) 
```
