### ISSUE TITLE
Incorrect RequestResult is received when adding trackRequestResult to an http request.

### ISSUE THREAD

**Issue by ozderko** [ngneat/elf#428]
### Which @ngneat/elf-* package(s) are the source of the bug?

requests-status

### Is this a regression?

No

### Description

I added it to the service
trackRequestResult([AuthRequestStatus.sendPhone]) and in the selector joinRequestResult([AuthRequestStatus.sendPhone])
But I get an incorrect status when the backend responds with a 400 error.
![image](https://user-images.githubusercontent.com/43940215/216146269-5709fba6-692e-4500-867c-6b7e6d3fbda4.png)

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
Can you provide a reproduction on stackblitz, please?

**Comment by NetanelBasal** [comment]
Something doesn't make sense in your image. The response is from POST signin request and not AuthRequestStatus.sendPhone

**Comment by ozderko** [comment]
I will add a photo of my service and the selector.
auth.selector.ts
![image](https://user-images.githubusercontent.com/43940215/216319467-39ef565b-f49f-4c05-a67c-72ced76f9b43.png)

auth.service.ts
![image](https://user-images.githubusercontent.com/43940215/216319356-8d244907-7bef-4dcc-ac4a-2e1c8f38df73.png)

**Comment by NetanelBasal** [comment]
Interesting, I'll check it.

**Comment by ozderko** [comment]
Just in case, I'll send a photo of my store, maybe I'm doing something wrong.
auth.repository.ts
![image](https://user-images.githubusercontent.com/43940215/216321288-2864ee19-9520-4149-8e83-c299460b8693.png)

**Comment by NetanelBasal** [comment]
https://stackblitz.com/edit/angular-cm1m1n?file=src%2Fmain.ts

It works fine. Please try to reproduce it.

**Comment by ozderko** [comment]
I think it's a problem on my end, I'm using Ionic and I tried to call catchError and nothing happened :c
Thanks for the help )

**Comment by ozderko** [comment]
It turned out to be even easier, I had an Interceptor that caught the error before it reaches the service)
