### ISSUE TITLE
Our firewall block the site https://ngneat.github.io/elf is listed in PH

### ISSUE THREAD

**Issue by Julian-B90** [ngneat/elf#450]
Our firewall is blocking the site https://ngneat.github.io/elf because it is ngneat.github.io is listed in PH.

You can check this at https://www.surbl.org/surbl-analysis

**Comment by shaharkazaz** [comment]
@Julian-B90 We are using GH pages for our docs. I don't see why it was listed there. any idea?

**Comment by Julian-B90** [comment]
Mhh not really. I have checked your site again with this tool https://www.urlvoid.com/scan/ngneat.github.io/ and it is only https://www.surbl.org/surbl-analysis that has a problem.

**Comment by Julian-B90** [comment]
@shaharkazaz  OK, I will do some research in the next few days

**Comment by Julian-B90** [comment]
Hey @shaharkazaz, you need to fill in the web form from SURBL https://www.surbl.org/surbl-analysis.

1. Enter your domain ngneat.github.io in the text box and click "Check".
2. Scroll down to the web form 
3. Enter your organisation details 
4. and click the "Request Removal" button

Alternatively, you can send an email to whitelist@surbl.org (the web form is recommended) with the following information:

1. Your Name
2. Your Email address (Should be in organization's own domain. Hotmail, Yahoo, gmail, etc., addresses may not be accepted.)
3. Organization name
4. Street address
5. Telephone number
6. Web site domain name or IP address
7. Explanation
 
I think your domain was blacklisted as false positive.

**Comment by shaharkazaz** [comment]
Can you try again? I redeployed the GH pages with an updated version of docusaurus.
Other than that TBH I have no idea... it's all managed by GH and built by docusaurus.

**Comment by Julian-B90** [comment]
Nice thank you 

![image](https://github.com/ngneat/elf/assets/4377396/c3998888-e430-46f7-8130-1d7d53985d46)
