### ISSUE TITLE
Cannot find module 'typescript'

### ISSUE THREAD

**Issue by zwjohn** [ngneat/elf#46]
### Which @ngneat/elf-* package(s) are the source of the bug?

CLI

### Is this a regression?

No

### Description

I was trying to follow the instruction on setting up CLI from here https://ngneat.github.io/elf/docs/cli and received the following errors when executing "npx @ngneat/elf-cli repo"
Note that, typescript is installed globally and in the project as well. Also I noticed that some elf packages are installed under dependencies instead of devDependencies in package.json, for example:
    "@ngneat/elf-cli-ng": "^1.0.0-beta.1",
    "@ngneat/elf-devtools": "^1.0.0-beta.4",

 

### Please provide the exception or error you saw

```true
npx @ngneat/elf-cli repo
npx: installed 193 in 10.354s
    Error: Cannot find module 'typescript'
    Require stack:
    - C:\Users\user\AppData\Roaming\npm-cache\_npx\9896\node_modules\@ngneat\elf-cli\lib\builders\repo-builder.js
    - C:\Users\user\AppData\Roaming\npm-cache\_npx\9896\node_modules\@ngneat\elf-cli\lib\commands\repo.js
    - C:\Users\user\AppData\Roaming\npm-cache\_npx\9896\node_modules\@ngneat\elf-cli\node_modules\@oclif\config\lib\plugin.js
    - C:\Users\user\AppData\Roaming\npm-cache\_npx\9896\node_modules\@ngneat\elf-cli\node_modules\@oclif\config\lib\config.js
    - C:\Users\user\AppData\Roaming\npm-cache\_npx\9896\node_modules\@ngneat\elf-cli\node_modules\@oclif\config\lib\index.js
    - C:\Users\user\AppData\Roaming\npm-cache\_npx\9896\node_modules\@ngneat\elf-cli\node_modules\@oclif\command\lib\command.js
    - C:\Users\user\AppData\Roaming\npm-cache\_npx\9896\node_modules\@ngneat\elf-cli\node_modules\@oclif\command\lib\index.js
    - C:\Users\user\AppData\Roaming\npm-cache\_npx\9896\node_modules\@ngneat\elf-cli\bin\run
    Code: MODULE_NOT_FOUND
```

### Please provide the environment you discovered this bug in

```true
DEV
```

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
You don't have typescript in your project?

**Comment by zwjohn** [comment]
it's there in the project's package.json under devDependencies, that's one of the default libraries for the angular project. I also installed typescript globally and it did not help

  "devDependencies": {
    "@angular-devkit/build-angular": "~12.2.10",
    "@angular/cli": "~12.2.10",
    "@angular/compiler-cli": "~12.2.0",
    "@types/jasmine": "~3.8.0",
    "@types/node": "^12.11.1",
    "@types/winbox": "^0.2.1",
    "jasmine-core": "~3.8.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.3.5",
    "@types/jquery": "^3.5.7"
  }

**Comment by NetanelBasal** [comment]
Try the latest version, please.

**Comment by zwjohn** [comment]
@NetanelBasal 
The typescript error is gone, and getting following error now

npx @ngneat/elf-cli repo
npx: installed 194 in 12.492s
? Store name widgets
? Select features Props, Entities, UIEntities, Active Id, Active Ids, Requests Cache, Requests Status
? Select CRUD operations Set, Create, Update, Delete
? idKey: widget-app
? Where you like to put this repository? D:\widget-app\src\app
    Error: Invalid index: The max index is 12, but 15 was specified.


Also, when installing cli, received "@ngneat/effects-hook@latest' is not in the npm registry." error. I was wondering why no one reporting these errors???


npx @ngneat/elf-cli install
npx: installed 194 in 17.123s
? Select packages @ngneat/elf (https://ngneat.github.io/elf/docs/store), @ngneat/elf-entities (https://ngneat.github.io/elf/docs/entities), @ngneat/elf-devtools (https://ngneat.github.io/e
lf/docs/devtools), @ngneat/elf-requests (https://ngneat.github.io/elf/docs/requests/requests-status), @ngneat/elf-state-history (https://ngneat.github.io/elf/docs/history), @ngneat/elf-per
sist-state (https://ngneat.github.io/elf/docs/persist-state), @ngneat/elf-pagination (https://ngneat.github.io/elf/docs/pagination), @ngneat/elf-cli-ng (https://ngneat.github.io/elf/docs/c
li)
? Select external packages @ngneat/effects (https://github.com/ngneat/effects), @ngneat/effects-hook (https://github.com/ngneat/effects#use-with-react), @ngneat/effects-ng (https://github.
com/ngneat/effects#use-with-angular), @ngneat/react-rxjs (https://github.com/ngneat/react-rxjs)
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@ngneat%2feffects-hook - Not found
npm ERR! 404
npm ERR! 404  '@ngneat/effects-hook@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by zwjohn** [comment]
> idKey: widget-app?

It can't be a string? has to be a number?

**Comment by NetanelBasal** [comment]
Does your entity have a property named `widget-app`?

**Comment by zwjohn** [comment]
Also, just FYI, I was trying out Akita initially, there were installation errors too, that's why I switched to Elf

**Comment by NetanelBasal** [comment]
You can try another solution that'll not cause you any errors :)

**Comment by zwjohn** [comment]
> Does your entity have a property named `widget-app`?

Nope, this is to use CLI to generate repo, I don't have an entity structure yet. However, my entity id will be a string, not a number. I guess I don't know what is the Idkey asked on the CLI prompt, so I just put a random one

**Comment by zwjohn** [comment]
> You can try another solution that'll not cause you any errors :)

Yes, I manually created the repo, that works. I just want to test out all features of this lib, so that we can decide if we can adopt it as our state management solution. Thanks for your quick fixes

**Comment by NetanelBasal** [comment]
The `idKey` is the property name of the `id`. It's `id` by default. You can read it in the docs.

**Comment by NetanelBasal** [comment]
Let me know if that was the issue, please.

**Comment by zwjohn** [comment]
> Let me know if that was the issue, please.

Oh, thanks for the explanation, now I understand what is idKey now, well, it will be definitely "id", I just think this can be defaulted, it should satisfy most cases and developers can change it later on if need. I will test again, and report back

**Comment by zwjohn** [comment]
> It is the default. You need to press enter and continue.

Got it, thanks. repo generation worked, however, the generated template was not fully populated

![image](https://user-images.githubusercontent.com/19634524/139917113-2493ec01-588e-4ea8-8ff5-f54741f9c4f2.png)

**Comment by NetanelBasal** [comment]
You're not using typescript v4.3.5+

**Comment by zwjohn** [comment]
The latest Angular CLI generated     "typescript": "~4.3.5"

**Comment by NetanelBasal** [comment]
It doesn't mean that you're using it. Can you please try to install the cli locally in your project, and run it?

**Comment by zwjohn** [comment]
I updated to "typescript": "~4.4.2",
![image](https://user-images.githubusercontent.com/19634524/139918319-aadeeef3-8228-49fe-a270-a879b2401418.png)

**Comment by zwjohn** [comment]
It's a local project.

**Comment by zwjohn** [comment]
Also, updating typescript higher version (greater than 4.3.5) will throw angular compilation errors when build or serve

 Generating browser application bundles (phase: setup)...D:\widget-app\node_modules\@angular\compiler-cli\src\typescript_support.js:65
            throw new Error("The Angular Compiler requires TypeScript >=" + minVersion + " and <" + maxVersion + " but " + version + " was found instead.");
            ^

Error: The Angular Compiler requires TypeScript >=4.2.3 and <4.4.0 but 4.4.4 was found instead.
    at checkVersion (D:\widget-app\node_modules\@angular\compiler-cli\src\typescript_support.js:65:19)
    at Object.verifySupportedTypeScriptVersion (D:\widget-app\node_modules\@angular\compiler-cli\src\typescript_support.js:70:9)
    at new NgtscProgram (D:\widget-app\node_modules\@angular\compiler-cli\src\ngtsc\program.js:47:38)
    at AngularWebpackPlugin.updateAotProgram (D:\widget-app\node_modules\@ngtools\webpack\src\ivy\plugin.js:310:32)
    at D:\widget-app\node_modules\@ngtools\webpack\src\ivy\plugin.js:187:24

**Comment by NetanelBasal** [comment]
I'll check it.

**Comment by NetanelBasal** [comment]
I've just tested it, and it works fine. Add `@ngneat/elf-cli` as dev dependency to your application and run `npx @ngneat/elf-cli repo`.

My guess is that you are running it globally and it uses your global typescript version. You can verify it by running `tsc --version`.

**Comment by zwjohn** [comment]
I used the "elf repo" command instead of  "npx @ngneat/elf-cli repo" and it generated a full repo template. However, I am seeing duplicated variable names. 

I created the repo manually, it wasn't too hard to do. This is more to help to test the CLI's functionality

![image](https://user-images.githubusercontent.com/19634524/139932105-1b793789-8550-4a2c-949e-44d240118e71.png)

**Comment by NetanelBasal** [comment]
It doesn't make sense to create both activeEntities and activeEntity, but I'll fix it anyway.

**Comment by NetanelBasal** [comment]
Closing this issue for now. If you have more issues let me know, and I'll fix them.

**Comment by zwjohn** [comment]
@NetanelBasal thanks very much for your speedy support, really appreciate it
