### ISSUE TITLE
Document site has been down for a while

### ISSUE THREAD

**Issue by zwjohn** [ngneat/elf#460]
The document site has been down for a while if there is a plan to fix it?

https://ngneat.github.io/elf/

**Comment by Julian-B90** [comment]
Mhh maybe it is this problem #450 and #457. 

Can you try to open it maybe with your handy or in a other network?

**Comment by zwjohn** [comment]
Yes, I can access the docs using data instead of home internet. It seems it has been blacklisted by my Asus router as a phishing website. Also, the status is "Detected" under SURBL using this link "https://www.urlvoid.com/scan/ngneat.github.io/". Maybe it is a good idea to host the docs site under another domain.
