### ISSUE TITLE
store.combine() is mutating emitted state object

### ISSUE THREAD

**Issue by nthonymiller** [ngneat/elf#461]
### Which @ngneat/elf-* package(s) are the source of the bug?

store

### Is this a regression?

No

### Description

Using `store.combine()` mutates the current object when emitting changes rather generating a new object reference causing downstream `rxjs` operators not to operator as expected.

The behavior is exhibited when using any operator that is maintaining references to emitted values such as `distinctUntilChanged` or `pairwise` operators.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/fvvzkm-842hjx?file=index.ts

### Please provide the exception or error you saw

```true
The previous and current object value are the same as the object is mutated.
```

### Anything else?

Using `store.combine()` should spread it's emitted value thus avoiding mutations.

### Do you want to create a pull request?

Yes

**Comment by hakimio** [comment]
Fixed in #462 ?
