### ISSUE TITLE
Docs site jumps focus to first stackblitz iframe

### ISSUE THREAD

**Issue by eduardoRoth** [ngneat/elf#47]
### Which @ngneat/elf-* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Not exactly a bug, but I find annoying/distracting that each time I enter a page in the docs site the stackblitz iframe gets focus and the scroll jumps there.

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
I know. I'll try to find a solution.

**Comment by NetanelBasal** [comment]
https://github.com/stackblitz/core/issues/1653

**Comment by NetanelBasal** [comment]
Should be OK now.
