### ISSUE TITLE
updateRequestsCache should take a ttl

### ISSUE THREAD

**Issue by SnorreDanielsen** [ngneat/elf#471]
### Which @ngneat/elf-* package(s) are relevant/releated to the feature request?

requests-cache

### Description

The "updateRequestCache" does take a ttl, but the plural version "updateRequestsCache" does not.

### Proposed solution

Give the ability to pass a ttl property to "updateRequestsCache", like so:
`store.update(updateRequestsCache(['keyOne', 'keyTwo'], { value: 'partial', ttl: 1000 }));`

### Alternatives considered

Currently this can be solved by looping through the entities and using the singuar version, "updateRequestCache".

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
Released
