### ISSUE TITLE
`getEntityByPredicate` is not available

### ISSUE THREAD

**Issue by EricPoul** [ngneat/elf#474]
### Which @ngneat/elf-* package(s) are the source of the bug?

entities

### Is this a regression?

No

### Description

There was no release after [this commit](https://github.com/ngneat/elf/commit/df17064f6916376f209e989b3577a2a4b63b6d0d) had gotten into `master` so `getEntityByPredicate` is not available for developers

### Do you want to create a pull request?

No

**Comment by EricPoul** [comment]
@NetanelBasal could you release `@ngneat/elf-entities` package?

**Comment by NetanelBasal** [comment]
Yes
