### ISSUE TITLE
trackRequestResult with staleTime and preventConcurrentRequest doesn't prevent concurrent requests

### ISSUE THREAD

**Issue by citruspress** [ngneat/elf#485]
### Which @ngneat/elf-* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Using trackRequestResult along with staleTime doesn't immediately prevent concurrent requests.

I have a failing test here: https://github.com/citruspress/elf/commit/86cd66067069a2aee623f0b99f5b1b5de5f859d1

I would be happy to have a look at this but just wanted to check if you had anyone else had any thoughts or input before.

I suspect the request is stale which is why concurrent requests can occur.

### Please provide a link to a minimal reproduction of the bug

https://github.com/citruspress/elf/commit/86cd66067069a2aee623f0b99f5b1b5de5f859d1

### Please provide the exception or error you saw

```true
In our application using elf, we sometimes se multiple requests when we've specified a stale time.
```

### Please provide the environment you discovered this bug in

```true
"@ngneat/elf-requests": "1.9.1",
```

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
You're welcome to create a PR
