### ISSUE TITLE
preStoreInit don't update with 'localStorageStrategy'

### ISSUE THREAD

**Issue by SatarisGIT** [ngneat/elf#496]
### Which @ngneat/elf-* package(s) are the source of the bug?

store, requests-data-source, persist-state

### Is this a regression?

No

### Description

As in title - when I use preStoreInit method with storage: localStorageStrategy - "new" overrided values don't also update on localstorage. I must manually invoke update method in preStoreInit (but also in hacky-way, inside setTimeout).

![image](https://github.com/ngneat/elf/assets/28608081/220062a3-0d7a-4f33-97b1-95a0dd8769d2)

**Comment by NetanelBasal** [comment]
You're welcome to create a PR
