### ISSUE TITLE
Strict mode TS does not accept idKey value other than 'id'

### ISSUE THREAD

**Issue by Ketec** [ngneat/elf#505]
### Which @ngneat/elf-* package(s) are the source of the bug?

store

### Is this a regression?

No

### Description

`withEntities<AssetEntity>({ idKey: 'uuid' })`
Results in type error:

`Argument type {idKey: "uuid"} is not assignable to parameter type {initialValue?: AssetEntity[] | undefined, idKey?: "id" | undefined} | undefined`

The type ends up as "id" here:
`IdKey extends string = "id"`

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-ykgajg?file=src%2Fapp%2Ftodos%2Fstate%2Ftodos.repository.ts

### Anything else?

"typescript": "4.9.5"
tsconfig is in strict mode

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
See https://ngneat.github.io/elf/docs/features/entities-management/entities#idkey
