### ISSUE TITLE
Elf-entities: SelectActiveEntity (v4.6.0) not working

### ISSUE THREAD

**Issue by MaxSassen** [ngneat/elf#507]
### Which @ngneat/elf-* package(s) are the source of the bug?

entities

### Is this a regression?

Yes

### Description

Were working with multiple developers.. newer developers with a clean repo have some issues with 'selectActiveEntity' it does't return anything. when downgrading '@ngneat/elf-entities' to 4.5.0 this issue is gone.

SelectActiveId, getActiveEntity etc.. still works.
Even the chrome 'redux devTool' shows the correct information  

Other developers that had an older version of the repo and upgraded the npm version from 4.5.0 to 4.6.0 doesn't have this problem.

Im not sure how this can be reproduced but 3 of our developers can't run it on 4.6.0, but haven't seen anyone else posting this issue

### Please provide the environment you discovered this bug in

```true
npm: 10.2.4
node: 20.11 (and 21.5.0)
```

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
I don't think we've touched this area and all the tests pass. You will need to add a reproduction.

**Comment by MaxSassen** [comment]
cant reproduce it on my pc/laptop .. will close it for now (thanks for the reply).
