### ISSUE TITLE
Store with a union type state: problematic type inference

### ISSUE THREAD

**Issue by thierry-st** [ngneat/elf#510]
### Which @ngneat/elf-* package(s) are the source of the bug?

store

### Is this a regression?

No

### Description

In the following example, the store will have an inferred state of type `never`

```
import { createStore, withProps } from "@ngneat/elf";

type Circle = { kind: "CIRCLE"; diameter: number };
type Square = { kind: "SQUARE"; edge: number };
type Shape = Circle | Square;

// The store has a state of 'never', instead of 'Shape'
const store = createStore(
  { name: "people" },
  withProps<Shape>({ kind: "CIRCLE", diameter: 2 })
);

// does not compile, because the store state is 'never'
store.update(() => ({ kind: "SQUARE", diameter: 1 }));
```

### Please provide a link to a minimal reproduction of the bug

https://github.com/thierry-st/ngneatelf-bug-report

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
The store type is an intersection of all passed state, so for example:

```ts
const store = createStore(
  { name: "people" },
  withProps<Shape>({ kind: "CIRCLE", diameter: 2 }),
  withProps<{ id: number }>({ id: number })
);
```

Results `Shape & { id: number }` which returns never.

**Comment by thierry-st** [comment]
Thanks for looking at this issue, but I don't understand how your answer is related to it.

What I was reporting is that one cannot create a store containing union type objects (so a store that just contains one object of type `Shape` in my example).

I don't get why you are making the issue more complex by throwing a `withProps<{ id: number }>({ id: number })` into the mix. Besides, note that the type `Shape & { id: number }` is not `never`, see [this playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAwglgJwMYBtoF4oG8oGs4B2AJgFxQBEMAkgEowAyAouQNxRFwCGAthMBAjIEArtwBGAqAF8WAKFCQoAZQCOwzggzY8hUhSUBFAKoBBGszYQiAcwhDREhNLkLoSgBadFmeMjRQAH2U1DQg5WQB6CKgQAHthKCROAihOAGc0uGsUzigAN04UYWhgWP1PRQAybDg9EXEBKXIAGig0srhgKDg0qAJYrvICCDyBclkkWII0roAPMg8vaGqsWvsGhCkoTCx8YjJKWgZmVo4ePgEyACZWtagARikgA).

**Comment by NetanelBasal** [comment]
See [this playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgdgSwPZwCpIJJ2BATgZwgGNhk4AeGAPigF4oAKGKCADxzgBN8oBDOEFAD8jANYAuWAEo6NAG5IEnKJLgQ5eGWw7dGAKChQJUBHABmeKBj0za8xZwPCrT1erwBuPaEhQAsngA5hDkAMrAvDgs7BBcPPwgANoAugA0UADSEILasboACrhIkLigWSA09PBk6Fg4BMSkKORO4ZEQiXAArgC2AEZ4yYnlyXpUXnpsYEilUGZdcCRkUES4EO1tOGHROjyFxfgAYrwkMyDkCekJVClUDE4AdE9gRWBHJ8AzCBD4kqE2kgA3lB8BEcJIArhgmF0gByF4HWHjFYoMwIQIQoIhUJwoio9FIqAAXyggKceLgoKga3wXQANsA6KSUeZ0UCielQe12cSJoYzDNGBSqcCKWjAukEW9iVAkGYoFL3qdcN98DIyYZDAB5PoAK0aD14+Hw6LgDBp9OADzF6PSNsCUi8mqgOv1JENxtN5p+loeXJwkteaqdxL0TjWwC6uDg1J9DL4PGB-ogmKh2LhiqRHhZ4tT0JxUFh9sJRK8RLD80WTRjAHcEMAABb7N7kVB3RWSVBSSTNpWfXDnVDpACiPTAoAAwvjAjQNbHI9HSU5DIrUsuc2yoAtOBA0WpOGvDKW9OWwz5oL3jsrzr30lPWTOmcCO1Be9n7ZJ7+Led5wNBR+OIBfuiTLbrupgQJwEznlAE4ILgRB0tA9DAqIpicJIABEE4YAAShOAAyw6YdmnAILwPQQPUqi9AMuA-jBoQAI5dLwaxPkY6FYaEACKMAAIK4cR2aQcENH9JYx6MQ2vC+PQcEIUhUAAD5QMxrFrBMegAPTaSCYLQAgPBqBouB6MKjJyEyqzrDgmwQAwdaNr2YQyZAdyoVxUDYXhhHEekZEUVReCSAATMSUhSHoQA)

**Comment by thierry-st** [comment]
Ah, I see, you were actually trying to explain why this issue arises in this library, interesting.

Looking at your playground, the issue comes from the inference of states intersection:

- the array of states is first converted to a union of states
- then it is converted to an intersection of states, using the  `UnionToIntersection` utility type

This latter `UnionToIntersection` is unfortunately too agressive. For example, it transforms `Circle | Square` into `Circle & Square`, which is `never`.

To solve the issue, we could directly compute the intersection of states via recursive type inference and variadic tuple types. Here is a [playground](https://www.typescriptlang.org/play?#code/PTAEAUCcFMDcEsD2BXAzqAJtAZvAdgC5J6iLagDkAstJAObQUBQwAVKAQJ4AO0oAqnmIAVRAElCtVNADGRRHgA8-AHygAvKAAU-UNAAeBaHgzoAhnk6gA-NoDWALgEBKDWtiJ4GUE7xxargZGJuhaTKCgjqD42LSgYkyu6u6eGOE28em+-pAA3ExMgiLikpDScsSK6QDKBGZGANp4yAC2AEa0ALoNANLQnJ1MKrmgrMAFIKAActAA7qDckIjciNLeWLiExKTk1LQMzFy8oDT00Iq19XxBxqagFpwNnQA0oH1WNyEQS7yQXO9qTSXIx6Qy3dANADeoAa4GiJHenWsThicQAaqAAL6vAB0eNRkFAACVOhkMQAyE77c5E14AnygZB4Ox4RCzPAFAwrP6gbBMioKUAyGBXYHnaqg4J3KDLVAAMTMckQkE4igerweKieKjCETxOMWsoVSsg8GgqCc1USTmhqDqRicpwYF1eFEN3FQFGGQoUuDojupLsoMl98DoXqxoEh6RDeDtoBgqGQABsCBooz68H6bdjQHarjmsfl0thldpY-HobG-a93ehMTsFj95YqCMqzahXNGIhEAPJtABWsgIOLMqFQYbwWkTKZH1bDr3ndGc+R7oH7Q7ko-Hk+n5tnOPzRlrzZX6UxBQiMAIyEgJBnqfu6Ft9ugAbOQbdza9IyX7+d1SukuEaYvkF5MHyeACiQszwAQAAWMoeoowg6nWTjCM4ThIS2JqqsIrwAKItNwXAAMKhnQajdgm0A3neUbpBEdbPExmbZoyJg4Pg0AYKxESgUw4FHHwOHGm2KqKDhrwUVmYaAhm6HfLKv6UU4sl+kWTAiaAxGkZwGlhumTIbDxGDFjpZHwJAMjJnwmjQnY+AYE4ABEZFiESZEADKEa5IwYPAZgtHRtC+K0HSEoJOnVAAjsgZgwOmjnOW51QAIr8AAgkSfkjLxDDhe0cTRTwfDVPBZjHJoVk2XZoAAD6gHFCUwMWkzCPBfAhWc3hHnw8DoCGkAwHIyZWASMDeGOlAVVVfCUtCXhFZFWLMBWaawOmwrQKKr5aLBCE4RclW8DqKUmG5Hleb5rmvIFwWhZATgAExYs4ryHYhzaKEtLmgM0xVRed0T-QAjO9zhMEAA) to illustrate the idea.

**Comment by thierry-st** [comment]
I've been playing around a bit to improve type safety of this `Merge` utility type. [Here is](https://www.typescriptlang.org/play?#code/PTAEAUCcFMDcEsD2BXAzqAJtAZvAdgC5J6iLagDkAstJAObQUBQwAVKAQJ4AO0oAqnmIAVRAElCtVNADGRRHgA8-AHygAvKAAU-UNAAeBaHgzoAhnk6gA-NoDWALgEBKDWtiJ4GUE7xxargZGJuhaTKCgjqD42LSgYkyu6u6eGOE28em+-pAA3ExMgiLikpDScsSK6QDKBGZGANp4yAC2AEa0ALoNANLQnJ1MKrmgrMAFIKAActAA7qDckIjciNLeWLiExKTk1LQMFKCz8AQAFhw8fKhmsVxMXLyggK5ANPTQgtexVRG19XxBxlMoAsnAanQANOk+lYASEIEteJAuNChhpQL8jHpDID0A0AN6gBrgaIkaGdJwxOIANVAAF9waAAHTMymQUAAJWgqAIWOCQJBYMGEVsNIAZM9XgwPjdoIpOdyGdCVFlQMg8HY8IhZnh8vdLqBJbKanVMbCgZyZIhIBhFNCGSCVGDIRFobycfDlrRkf1UZoMf9sXCGukCUSSaAyRS8LE2TT6elmYzWRyuTyzeZLGCmEKMmKJft3nhPrL5QRFf1lREnGqNVqdQUmAYVkjQNg1RUFKAZDA-v7FNU3XCoMtUAAxMxyK2cRQg+2WR2dFRhCKJxYj8eTyDwLlOaqJJwE7l-JyG-sMihr7ioCjDLsKXB0E8Fs+US3R+B0G900B49Jv7mgDAqDIAANjymgEm+D4HvSoBHkYMF0rqETYFa2j-jykH3h+DKXugtI7AsCJjhOBBWtuqCuL+EQRAA8m0ABWsgEIyZioKgH54FoQGgSxUE4Xe750M4+Q0aA9FMXIrHsZx3FcrxjLwdAuHESJ6S0gUEQwAQyCQCQPFgcC6CHia0BPm8L4XsRN4jPxj4Gs+1TnnZX60vkGlMG2eAdiQxxnMOV6KMIS54U4wjOE4AUkZu07CAyACiLTcFwADC2F0Go1GAdAOl6T+6QRHhzo0XZ1YmDg+DQBgxVuUwHkPHwUUbmRkDTlFDJpUJagQURI6RcRtnpU4nUPkheqPIlyWcCNH5omqGyVRguoNaAKXwJAMggXwPV2PgGBOAARClYjsilAAy8UHSMGDwGYLQ5bQvitB0bK1St1QAI7IGYMBogSu0mId1QAIr8AAguyl0jFVDBPe0cRvfq1SnGYjyaGtG1baAAA+6JfT90C6pMwinHw91vN4SnROglqQDAcggVYrIwN4bGUMjqN8OKBJeHDL10swGGgLAaLdtAvamVofmnFF-Yo7wS7-Xth3HadF0HQyN13Q9kBOAATHSzgMtLss8-toDNPDr2K9E5sAIyG84TBAA) a type safe alternative, which is uglier though.

You can test that when using this `Merge` utility type in the `createState`, it ensures that the hand written keys `'props'` and `'config'` are in sync with the `PropsFactory` type

**Comment by NetanelBasal** [comment]
Yes, all the tests passes. I'm releasing a new version. Thanks, I didn't have time to fix it.

**Comment by thierry-st** [comment]
Excellent news, I'm glad I could contribute to your library. Thanks for your work!
