### ISSUE TITLE
@ngneat/elf-requests does not support removing a single request cache by key.

### ISSUE THREAD

**Issue by HeathJared** [ngneat/elf#515]
### Description

The package `@ngneat/elf-requests` provides a function `clearRequestsCache`, but this function does not support passing in a key as the argument.

### Proposed solution

Add a new operator `deleteRequestsCache(key: CacheRecordKeys<S>)`  to delete an individual cache from the store by key.

### Alternatives considered

Add an overload `clearRequestsCache` to provide the same functionality described above.

### Do you want to create a pull request?

No

**Comment by VasilyShelkov** [comment]
Am I right in thinking this never made it to the released `elf-requests` package ?
