### ISSUE TITLE
Incompatible with yarn

### ISSUE THREAD

**Issue by mdudek** [ngneat/elf#58]
### Which @ngneat/elf-* package(s) are the source of the bug?

CLI

### Is this a regression?

No

### Description

Yarn add command `yarn add @ngneat/elf-cli` throws an exception.

### Please provide the exception or error you saw

```true
An unexpected error occurred: "could not find a copy of typescript to link in c:\\projects\\angular-tour-of-heroes\\node_modules\\@ngneat\\elf-cli\\node_modules".
```

### Do you want to create a pull request?

No

**Comment by hakimio** [comment]
At least with `yarn v1.22.15` it installs without any issues. Maybe there is an issue on your side?

**Comment by mdudek** [comment]
This is my setup:

1. created new app :  `ng new myApp`
2. `cd myApp`
3. `yarn add @ngneat/elf-cli`
4. `An unexpected error occurred: "could not find a copy of typescript to link  ...`

Node
Angular-cli 13.0.3
Node v14.18.0
npm 6.14.15
yarn 1.22.17

**Comment by hakimio** [comment]
I was able to reproduce it following your steps. Seems to be an issue in Angular v13 project.
On a bright side `@ngneat/elf-cli-ng` installs without any issues.
Might also be [an issue with yarn](https://github.com/yarnpkg/yarn/issues/6806) itself.

**Comment by hakimio** [comment]
Maybe the issue is that TypeScript is listed in `package.json` twice with two different versions: in `dependencies` and `peerDependencies`. [The one in `dependencies` (`^4.3.5`)](https://github.com/ngneat/elf/blob/dev/packages/cli/package.json#L27) most likely is causing issues.

**Comment by mdudek** [comment]
I noticed that. I wanted to change it, but I was not able to build the project (There are no build instructions, I have already opened another issue for that).

**Comment by mdudek** [comment]
Removing typescript from `peerDependencies` definitely solves the issue.

I have found a workaround. Just add typescript version to resolutions section in package.json 
```  
"resolutions": {
    "typescript": "4.4.4"
}
```

**Comment by hakimio** [comment]
It's nice that you've found a workaround, but the real solution should be to remove TS from _hard_ dependencies and keep the peer dependencies.

**Comment by NetanelBasal** [comment]
We can do this, but when you install it globally you need to remember to install it

**Comment by NetanelBasal** [comment]
@mdudek did you installed it globally?

**Comment by mdudek** [comment]
I'm using local packages, it's much better for versioning @NetanelBasal

**Comment by NetanelBasal** [comment]
Yes, I also always prefer to install locally.
