### ISSUE TITLE
DevTools: time travel broken

### ISSUE THREAD

**Issue by petterhoel** [ngneat/elf#63]
### Which @ngneat/elf-* package(s) are the source of the bug?

devtools

### Is this a regression?

No

### Description

Time travel in the dev tools is not working for me. See demo in gif showing an api call for data and trying to step back with the dev tools. (edit) Clarification: Dev tools shows correct data, but app UI is not following.
![2021-11-26_09-12-10 (1)](https://user-images.githubusercontent.com/1263775/143553321-bb1af063-2d08-40d0-9523-8353c21e581e.gif)

In another app running both Akita and Elf side by side, time travel worked with Akita but not with Elf. 
In both cases this is how I am calling devTools for elf

```
// app.module.ts

import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { AboutComponent } from './about.component';
import { EditComponent } from './edit.component';
import { ElfListComponent } from './elf-list.component';
import { CommonModule } from "@angular/common";
import { AlfComponent } from './alf.component';
import { HttpClientModule} from "@angular/common/http";
import { ElfFormComponent } from './elf-form.component';
import { FormsModule } from "@angular/forms";
import { environment } from "../environments/environment";
import { devTools } from "@ngneat/elf-devtools";

!environment.production ? devTools() : null;

@NgModule({
  declarations: [
    AppComponent,
    AboutComponent,
    EditComponent,
    ElfListComponent,
    AlfComponent,
    ElfFormComponent
  ],
  imports: [
    BrowserModule,
    CommonModule,
    HttpClientModule,
    FormsModule,
    AppRoutingModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

### Please provide a link to a minimal reproduction of the bug

https://github.com/petterhoel/elf-dev-tools-bug-repro

### Please provide the environment you discovered this bug in

```true
# macOs M1:
FireFox@latest
Edge@latest
Chrome@latest

# Windows10
FireFox@latest


"dependencies": {
    "@angular/animations": "~13.0.0",
    "@angular/common": "~13.0.0",
    "@angular/compiler": "~13.0.0",
    "@angular/core": "~13.0.0",
    "@angular/forms": "~13.0.0",
    "@angular/platform-browser": "~13.0.0",
    "@angular/platform-browser-dynamic": "~13.0.0",
    "@angular/router": "~13.0.0",
    "@ngneat/effects-ng": "^1.0.0-beta.0",
    "@ngneat/elf": "^1.0.0-beta.5",
    "@ngneat/elf-devtools": "^1.0.0-beta.4",
    "@ngneat/elf-entities": "^1.0.0-beta.10",
    "@ngneat/elf-requests": "^1.0.0-beta.13",
    "rxjs": "~7.4.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.1.0-next.2",
    "@angular/cli": "~13.1.0-next.2",
    "@angular/compiler-cli": "~13.0.0",
    "@angular/language-service": "~13.0.2",
    "@ngneat/elf-cli-ng": "^1.0.0-beta.1",
    "@ngneat/elf-cli": "1.0.0-beta.12",
    "@types/node": "^12.11.1",
    "tuicss": "^2.1.1"
  }
```
```


### Anything else?

_No response_

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
That's probably because it runs outside the Angular Zone.

**Comment by petterhoel** [comment]
Is there anything I as an app developer can do to control this? 

I tried moving the `devToos()` call to an app initializer and even constructor of `AppComponent` to no avail.

**Comment by petterhoel** [comment]
Looking at the AkitaDevTools code I gather there is a little more work to make NgZone devtools aware than just calling devTools() at the right place. 

So this is probably not a bug as such, but hopefully a future feature. 

Closing this so the devs can feel free to implement or not in their own time frame.
