### ISSUE TITLE
State change issue

### ISSUE THREAD

**Issue by mdudek** [ngneat/elf#66]
### Which @ngneat/elf-* package(s) are the source of the bug?

store

### Is this a regression?

No

### Description

I have modified your Todos example project to create reproduction example of issue, that I'm facing now in my Project. I added state prop 'processing' and it's value is unexpectedly changed when filter is modified. There is a statement in repos constructor that  monitors todos & filter modifications. It sets 'processing' to true and back to false after 3s as some data processing simulation. It works correctly first time on load, but switches back from true to false immediately when you change filter by button.  The 'processing' prop value is rendered to UI & logged to console.

### Please provide a link to a minimal reproduction of the bug

https://angular-ivy-v6pzpb.stackblitz.io

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
What you mean is unclear to me. You are subscribed to the following:
```ts
combineLatest([this.todos$, this.filter$])
```

When you update the filter property, it runs and calls `setProcessingState`.

**Comment by mdudek** [comment]
Yes, but check console what happened when setProcessingState(true) is called.

1. Open app
2. Click 'Active' button

Expected: The 'processing' property should be set to true, after 3s is switched back to false.
The bug: The 'processing' property is set to true, but immediately switched back to false.
