### ISSUE TITLE
createRequestDataSource data$ type error when typing withRequestsStatus with some passed type

### ISSUE THREAD

**Issue by EricPoul** [ngneat/elf#72]
### Which @ngneat/elf-* package(s) are the source of the bug?

requests-data-source

### Is this a regression?

No

### Description

If you pass a type to `withRequestsStatus` and try to create dynamic dataSource you will see a type error. And this is correct since `RequestKey` is already not any string but a specific one.
![image](https://user-images.githubusercontent.com/31760529/144832121-5619a2cd-0c29-49a8-951b-d043db2b2bf7.png)
![image](https://user-images.githubusercontent.com/31760529/144831984-7b24dd31-e89a-44a4-84a4-7621dfffceeb.png)
![image](https://user-images.githubusercontent.com/31760529/144832607-d4720704-9f60-4608-8373-1bc38fcb7cda.png)

I couldn't reproduce it on a `stackblitz` but I could in `elf` `ng` app when I add a type to `withRequestsStatus`(`users.repository.ts`).

### Please provide the exception or error you saw

```true
TS2322: Type '(key: number) => Observable<User | undefined>' is not assignable to type '() => Observable<User | undefined>'.  request-data-source.ts(76, 3): 

The expected type comes from property 'data$' which is declared here on type '{ dataKey: "user"; data$: () => Observable<User | undefined>; requestKey?: "users" | undefined; store: Store<StoreDef<{ requestsStatus: Record<"users", StatusState>; } & { ...; } & { ...; }>, { ...; } & ... 1 more ... & { ...; }>; idleAsPending?: boolean | undefined; requestStatusOptions?: { ...; } | undefined; }'
```

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
It works fine: https://github.com/ngneat/elf/blob/9745f87899cae2be7125c6eb6354af94be80ab20/packages/requests/src/lib/requests-status.spec.ts#L20

I'm not sure what your issue is.

**Comment by EricPoul** [comment]
@NetanelBasal it does but only for DataSource. If you try to make dynamic dataSource that it will show an error

**Comment by EricPoul** [comment]
This is what i get if I add a type and create a dynamic dataSource in your tests
![image](https://user-images.githubusercontent.com/31760529/144843309-bf4a0c59-8cf1-4764-8f5b-7c7142c66044.png)

**Comment by NetanelBasal** [comment]
Can you paste the code here, please? I'll try in my IDE

**Comment by EricPoul** [comment]
As I understood, when you set a type to `withRequestsStatus` it no longer pass next condition
``` 
data$: string extends RequestKey
    ? (key: any) => Observable<Data>
    : () => Observable<Data>;
``` 

for example 
```
    withRequestsStatus<'users'>()
    string not extends 'users'
```

**Comment by EricPoul** [comment]
```
export interface User {
  id: number;
  name: string;
  email: string;
}

const { state, config } = createState(
  withEntities<User>(),
  withRequestsStatus<'users'>()
);
const store = new Store({ name: 'users', state, config });

const userDataSource = createRequestDataSource({
    store,
    data$: (key: number) => store.pipe(selectEntity(key)),
    dataKey: 'user',
    requestStatusOptions: { groupKey: 'users' },
});
```

**Comment by EricPoul** [comment]
I had a solution based on overloads where if you set data as `(key: number) => Observable<Data>` that you can't add `requestKey`

**Comment by NetanelBasal** [comment]
Sounds good. Please create a PR.

**Comment by EricPoul** [comment]
Just one question. `requestKey` is required property for plain `DataSource` or it can remain optional?

**Comment by NetanelBasal** [comment]
Required. Otherwise, we can't know to which key you refer.

**Comment by EricPoul** [comment]
In this case, if you don't set `requestKey` it'll be recognized as `dynamic` `DataSource` even if you set `data` as `() => Observable<Data>` since `key` has type `any` and `() => Observable<Data>` is equal to `(key: any) => Observable<Data>` in this case. But if you set `requestKey` it'll be recognized as `plain` `DataSource` and you won't be allowed to set `data` as `(key: any) => Observable<Data>` instead of `() => Observable<Data>`.
Is it ok?

**Comment by NetanelBasal** [comment]
- If the user provides `requestKey` the returned value should be `DataSource`.

- If the user didn't provide `requestKey` the returned value should be `DynamicKeyDataSource`.

**Comment by NetanelBasal** [comment]
Thanks!
