### ISSUE TITLE
Can't select destination directory

### ISSUE THREAD

**Issue by kopach** [ngneat/elf#81]
### Which @ngneat/elf-* package(s) are the source of the bug?

CLI

### Is this a regression?

No

### Description

See results from my terminal below

```bash
npx @ngneat/elf-cli repo                                                      npm8.2.0  node14.18.2           
? Store name monitors
? Select features Props
? Where you like to put this repository? (Use arrow keys or type to search)
  No results...
 ```
 
 I've also tried go install tool globally and use `elf` command directly — same result. Also tried in different environment `npm6.14.12  node12.22.1`

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
We're using https://github.com/adelsz/inquirer-fuzzy-path, so the issue is probably there. Are you using windows?

**Comment by kopach** [comment]
Mac OS Monterey 12.0.1

**Comment by kopach** [comment]
Ok. I've found defect, it's in elf CLI. Let me rise PR

**Comment by kopach** [comment]
Ok. let me explain first the issue. It's in this line `excludeFilter: (nodePath) => nodePath.includes('.')`
In my case, literally every `nodePath` will contain dot (.) character as one of my top folders contain it. e.g. `path/some.path/path/path`. Therefore app folders are excluded for me. So, I have following suggestions:

1. fallback path to config, so user at least can select something as fallback `default: process.cwd(),`
2. use `git` to identify what folders to exclude. e.g. I wouldn't want to see folders like `dist`/`build` or similar on the list. DO you have any `git` wrapping node libraries added to the project already for reuse in this case?

**Comment by strigefleur** [comment]
I'd also suggest to refactor generated repo path selection dialog in some way - we have a complex project structure with lots of directories so it's quite uncomfortable to scroll through all that text output to find just one required line.
Could be an option with default relative path for repo generation like **repoLibrary**.

**Comment by NetanelBasal** [comment]
@kopach I like the second option. We don't have such a library. Do you want to create a PR?

@strigefleur, there is a search option.

**Comment by NetanelBasal** [comment]
Performance was adversely affected by adding the `gitignore` functionality. I've added an option to provide a different implementation of the `fuzzysearch` plugin since your convention for folders isn't commonly used. 

https://ngneat.github.io/elf/docs/cli#fuzzypath

**Comment by zihotki** [comment]
@NetanelBasal I know that this is a closed issue but I was stumbled into the same bug. We commonly use dots in the folder names and that causes the issue above. I wonder what's the logic behind ignoring all folders that contain a dot '.'? From what I know, usually only folders which start with dot should be ignored. But currently it checks for a dot in any position.

The reason why I'm asking is that it may become a roadblock for a newcomer, from my experience I don't like to bump into issues from the start, it leaves a bad taste.

**Comment by NetanelBasal** [comment]
Why is it done? I need to remember why :). I will change it to `startWith` if there is no reason.

**Comment by NetanelBasal** [comment]
We get the full path in the function, e.g., `path/to/foo`. Although I could split and check each segment using `startsWith`, I used the `includes` function for performance reasons. 

I'm curious, what is the motivation for using dots in folders? I haven't seen this pattern very often.

**Comment by NetanelBasal** [comment]
@flawesomesoft what about https://ngneat.github.io/elf/docs/cli/#fuzzypath?

**Comment by flawesomesoft** [comment]
> @flawesomesoft what about https://ngneat.github.io/elf/docs/cli/#fuzzypath?

Thanks for the quick reply @NetanelBasal  

I've just tried to implement the fuzzy path.
I'm assuming the **elf.config.js** lies at the root of the project for which the elf-modules are installed.

### elf.config.js file
```
module.exports = {
  cli: {
    fuzzypath: {
      rootPath: process.cwd,
      excludePath(path) {
        path.includes('node_modules')
      },
      excludeFilter(path) {
        path.startsWith('.')
      }
    }
  }
}
```



### package.json
```
{
  "name": "domain",
  "version": "0.0.1",
  "peerDependencies": {
    "@angular/common": "^13.3.0",
    "@angular/core": "^13.3.0"
  },
  "dependencies": {
    "@ngneat/elf": "^2.1.0",
    "@ngneat/elf-cli": "^3.0.0",
    "@ngneat/elf-cli-ng": "^1.0.0",
    "@ngneat/elf-entities": "^4.3.1",
    "tslib": "^2.3.0"
  },
  "elf": {
    "cli": {
      "repoTemplate": "class",
      "inlineStoreInClass": true,
      "idKey": "_storeId",
      "repoLibrary": "repositories",
      "plugins": ["@ngneat/elf-cli-ng"]
    }
  }
}
```


So i assume **path.startsWith('.')** for excludeFilter will no longer exclude the paths like "_Project1.Web_"

Yet, I still get **no results**:

```
npx @ngneat/elf-cli repo
? Store name test
? Select features Props, Entities, Active Id, Active Ids
? Select CRUD operations Set, Create, Update, Delete
? idKey: _idKey
? Where you like to put this repository?
  No results...
```

Unfortunately I cannot show you the full path but i can assure there is no leading "." in it

**Comment by NetanelBasal** [comment]
@flawesomesoft try v3.0.1

**Comment by flawesomesoft** [comment]
Thank you so much @NetanelBasal 

[This ](https://github.com/ngneat/elf/commit/b2a44ace826042e91913ae62c72eea22d80d9b76) perfectly fixed the problem i had.

Means, it will work now as you mentioned in your prior post:

> We get the full path in the function, e.g., `path/to/foo`. Although I could split and check each segment using `startsWith`, I used the `includes` function for performance reasons.
