### ISSUE TITLE
Undo History Glitch

### ISSUE THREAD

**Issue by SonyStone** [ngneat/elf#91]
### Which @ngneat/elf-* package(s) are the source of the bug?

state-history

### Is this a regression?

No

### Description

When `stateHistory` is paused, the previous value is partially retained when updating.

https://github.com/ngneat/elf/blob/master/packages/state-history/src/lib/state-history.ts#L62
```typescript
      .pipe(pairwise()) // ← the previous value is stored in this operator
      .subscribe(([past, present]) => {
        if (this.skipUpdate || this.paused) {
          return;
        }
        …
```
Need to change to
```typescript
      .pipe(
        filter(() => !(this.skipUpdate || this.paused)), // ← Need to skip the value before it saves
        pairwise(),
      ).subscribe(([past, present]) => {
      …
```

Exactly the same problem exists in Akito
https://github.com/datorama/akita/blob/master/packages/akita/src/lib/plugins/stateHistory/stateHistoryPlugin.ts#L94

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/typescript-bjbno4?file=index.ts

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
You're welcome to create a PR
